import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {build} from 'esbuild';
import electron from 'electron';

test('real theme switches cover settings, session, modal, editor and terminal without restarting or losing input', {skip:process.platform==='linux'&&!process.env.DISPLAY,timeout:30000}, async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-appearance-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const root=fileURLToPath(new URL('../',import.meta.url));
 const source=`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import ${JSON.stringify(join(root,'src/style.css'))};import{AppearanceProvider}from ${JSON.stringify(join(root,'src/Appearance.tsx'))};import{Studio}from ${JSON.stringify(join(root,'src/Studio.tsx'))};import{EditorSettings}from ${JSON.stringify(join(root,'src/EditorSettings.tsx'))};import{GeneralSettings}from ${JSON.stringify(join(root,'src/GeneralSettings.tsx'))};import{InteractiveTerminal}from ${JSON.stringify(join(root,'src/InteractiveTerminal.tsx'))};import{Avatar,Modal}from ${JSON.stringify(join(root,'src/ui.tsx'))};import{EditorView}from'@codemirror/view';
 window.darkThemeFacet=EditorView.darkTheme;window.flush=flushSync;window.terminalOpens=0;window.terminalCloses=0;
 const call=async(method,a)=>{if(method==='files')return[{name:'example.js',path:'example.js',directory:false}];if(method==='file.read')return{content:'const greeting = "Hello";\\n    console.log(greeting);',hash:'initial',canonicalRoot:'/synthetic-appearance-fixture'};if(method==='draft.read')return null;if(method==='project.context')return{root:'/synthetic-appearance-fixture',branch:'main'};if(method==='language.diagnostics')return [];if(method==='composer.read')return{text:'',images:[],revision:0};if(method==='terminal.open'){window.terminalOpens++;return{id:'fixture-pty'};}if(method==='terminal.read')return{sequence:1,data:'Local terminal fixture\\r\\n\\x1b[32mReady\\x1b[0m  no command executed\\r\\n$ ',exited:false};if(method==='terminal.close'){window.terminalCloses++;return true;}return {};};window.rpo={invoke:call,subscribeTerminal:()=>()=>{},subscribeDictation:()=>()=>{}};
 const entries=[{id:'u',role:'user',text:'Review the proposed changes.',at:new Date().toISOString()},{id:'a',role:'assistant',text:'The local draft is ready for review.',at:new Date().toISOString()}];const lane={id:'l',ownerId:'me',owner:'Alex',provider:'codex',status:'done',entries,files:[]};const session={id:'s',workspaceId:'w',title:'Appearance preview',branch:'main',status:'active',description:'',lanes:[lane],plan:[],comments:[],files:[],diff:''};const state={workspaces:[{id:'w',name:'Preview'}],sessions:[session],memories:[],approvals:[{id:'approval',sessionId:'s',laneId:'l',status:'pending',owner:'Alex',provider:'codex',prompt:'Review before execution',files:[],overlaps:[]}],members:[{id:'me',name:'Alex'},{id:'other',name:'Bo'}],me:{id:'me',roles:{w:'owner'}},local:{paths:{w:'/synthetic-appearance-fixture'},sessionPaths:{},providers:[],name:'Alex',online:true}};
 function App(){const[value,setValue]=useState();const[mounted,setMounted]=useState(true);const[modal,setModal]=useState(false);window.appearance=patch=>flushSync(()=>setValue(old=>({...old,...patch})));window.unmountAppearance=()=>flushSync(()=>setMounted(false));window.modal=open=>flushSync(()=>setModal(open));const content=<div className='preview'><aside className='settings-preview'><h1>设置</h1><GeneralSettings call={call}/><EditorSettings call={call}/></aside><div className='work-preview'><header className='session-topbar'><strong>Appearance preview</strong><div id='avatars'><Avatar name='Alex'/><Avatar name='Bo'/><Avatar name='Alex'/></div></header><div id='studio'><Studio state={state} session={session} call={call} notify={()=>{}} onAddLane={()=>{}} onShare={()=>{}} onRepos={()=>{}}/></div><div id='terminal'><InteractiveTerminal bridge={window.rpo} workspaceId='w' sessionId='s'/></div></div>{modal&&<Modal title='确认操作' close={()=>setModal(false)}><p>Review the local change.</p><input aria-label='确认名称' defaultValue='Preview'/><button className='button primary'>确认</button></Modal>}</div>;return mounted?<AppearanceProvider value={value}>{content}</AppearanceProvider>:<p>Appearance unmounted</p>;}createRoot(document.getElementById('root')).render(<App/>);window.view=()=>{const el=document.querySelector('#studio .cm-editor');return el?EditorView.findFromDOM(el):null;};`;
 await build({stdin:{contents:source,loader:'tsx',resolveDir:root},outfile:join(dir,'ui.js'),bundle:true,format:'iife',platform:'browser',logLevel:'silent'});
 await writeFile(join(dir,'index.html'),`<html data-theme="fixture-original"><head><link rel="stylesheet" href="ui.css"><style>html,body,#root{height:100%;margin:0}.preview{height:100%;display:grid;grid-template-columns:330px 1fr}.settings-preview{padding:20px;overflow:auto;border-right:1px solid var(--line)}.work-preview{min-width:0;display:flex;flex-direction:column}#studio{height:700px;display:flex;min-height:0;flex:1}#terminal{height:170px;flex-shrink:0}#avatars{display:flex;gap:8px;margin-left:auto;padding:8px}.modal-body{display:grid;gap:20px}</style></head><body><div id="root"></div><script src="ui.js"></script></body></html>`);
 // The body below exercises actual components; synthetic RPC never opens a shell.
 const validate=async()=>{
  const check=(ok,message)=>{if(!ok)throw Error(message);};
  const wait=async fn=>{const until=Date.now()+5000;while(Date.now()<until){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('UI condition failed: '+fn.toString());};
  const color=(selector,property='backgroundColor')=>getComputedStyle(document.querySelector(selector))[property];
  const contrast=(fg,bg)=>{const luminance=s=>{const values=s.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return values[0]*.2126+values[1]*.7152+values[2]*.0722;};const a=luminance(fg),b=luminance(bg);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);};
  await wait(()=>document.documentElement.dataset.theme==='dark'&&window.terminalOpens===1);
  const darkSetting=color('.general-settings fieldset'),darkTerminal=color('.xterm-scrollable-element');
  document.querySelector('#studio button[title="example.js"]').click();await wait(()=>window.view());const view=window.view(),terminal=document.querySelector('#terminal .xterm');
  window.flush(()=>view.dispatch({changes:{from:0,to:view.state.doc.length,insert:'const unsaved = 42;\n    console.log(unsaved);'},selection:{anchor:5}}));
  window.appearance({theme:'light'});await wait(()=>document.documentElement.dataset.theme==='light');await wait(()=>color('.xterm-scrollable-element')==='rgb(250, 251, 252)');
  check(color('.general-settings fieldset')!==darkSetting,'settings did not change');check(color('.xterm-scrollable-element')!==darkTerminal,'terminal colors did not change');
  for(const selector of ['.general-settings fieldset','.editor-settings fieldset','.session-rail','.agent-dock','.editor-pane','.lane-header','.approval-card']){const el=document.querySelector(selector);check(contrast(getComputedStyle(el).color,getComputedStyle(el).backgroundColor)>=4.5,'low text contrast: '+selector);}
  check(color('.cm-editor')==='rgb(250, 251, 252)','editor background is not light');check(color('.cm-gutters')==='rgb(240, 243, 246)','editor gutter still dark');check(!view.state.facet(EditorView.darkTheme),'CodeMirror syntax theme is still dark');check(color('.rpo-code-minimap')==='rgb(239, 243, 247)','minimap still dark');
  check(window.view()===view&&view.state.doc.toString().includes('unsaved')&&view.state.selection.main.anchor===5,'theme lost editor document/selection');check(document.querySelector('#terminal .xterm')===terminal&&window.terminalOpens===1&&window.terminalCloses===0,'theme restarted terminal');
  const avatars=Array.from(document.querySelectorAll('#avatars .avatar'));const colors=avatars.map(el=>getComputedStyle(el).backgroundColor);check(colors[0]!==colors[1]&&colors[0]===colors[2],'avatar colors not stable');for(const el of avatars)check(contrast(getComputedStyle(el).color,getComputedStyle(el).backgroundColor)>=4.5,'avatar contrast too low');
  window.appearance({collaboratorColors:false});check(new Set(avatars.map(el=>getComputedStyle(el).backgroundColor)).size===1,'monochrome not applied');check(avatars.map(el=>el.title).join(',')==='Alex,Bo,Alex','names changed');window.appearance({collaboratorColors:true});check(avatars.every((el,i)=>getComputedStyle(el).backgroundColor===colors[i]),'avatar colors changed after restore');
  window.modal(true);check(color('.modal')==='rgb(255, 255, 255)','modal remained dark');check(contrast(color('.modal','color'),color('.modal'))>=4.5,'modal contrast');document.querySelector('.modal input').focus();check(document.activeElement?.getAttribute('aria-label')==='确认名称','input focus missing');window.appearance({theme:'dark'});check(document.activeElement?.getAttribute('aria-label')==='确认名称','theme stole focus');check(color('.general-settings fieldset')===darkSetting,'dark settings not restored');await wait(()=>color('.xterm-scrollable-element')===darkTerminal);check(view.state.facet(EditorView.darkTheme),'dark syntax not restored');check(window.terminalOpens===1&&window.terminalCloses===0,'round-trip restarted terminal');
  window.modal(false);window.appearance({theme:'light'});return true;
 };
 // EditorView is exposed only to inspect the real editor's theme facet.
 const validateSource='('+validate.toString().replaceAll('EditorView.darkTheme','window.darkThemeFacet')+')()';
 await writeFile(join(dir,'runner.cjs'),`const{app,BrowserWindow}=require('electron');const fs=require('node:fs/promises');app.disableHardwareAcceleration();let win;app.whenReady().then(async()=>{win=new BrowserWindow({show:false,width:1440,height:1080,webPreferences:{backgroundThrottling:false,offscreen:true}});win.webContents.on('console-message',event=>console.log('renderer:',event.message));await win.loadFile(${JSON.stringify(join(dir,'index.html'))});await win.webContents.executeJavaScript(${JSON.stringify(validateSource)});if(process.env.RPO_APPEARANCE_SCREENSHOT_DIR){await fs.mkdir(process.env.RPO_APPEARANCE_SCREENSHOT_DIR,{recursive:true});await win.webContents.executeJavaScript("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await fs.writeFile(require('node:path').join(process.env.RPO_APPEARANCE_SCREENSHOT_DIR,'light.png'),(await win.webContents.capturePage()).toPNG());await win.webContents.executeJavaScript("window.appearance({theme:'dark'});new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await fs.writeFile(require('node:path').join(process.env.RPO_APPEARANCE_SCREENSHOT_DIR,'dark.png'),(await win.webContents.capturePage()).toPNG());}await win.webContents.executeJavaScript("window.unmountAppearance();if(document.documentElement.dataset.theme!=='fixture-original')throw Error('Provider failed to restore original html attribute')");console.log('APPEARANCE_PASS');win.destroy();app.exit(0);}).catch(error=>{console.error(error);if(win)win.destroy();app.exit(1);});`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
 const result=await new Promise((resolve,reject)=>{const child=spawn(electron,[join(dir,'runner.cjs')],{env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>output+=v);const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('Appearance UI timeout\n'+output));},25000);child.once('error',reject);child.once('exit',code=>{clearTimeout(timer);resolve({code,output});});});assert.equal(result.code,0,result.output);assert.match(result.output,/APPEARANCE_PASS/);
});
