import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{fileURLToPath}from'node:url';import{spawn}from'node:child_process';import{build}from'esbuild';import electron from'electron';
test('multiple real Agent views move between editor tabs and dock without remounting, changing roots or executing',{skip:process.platform==='linux'&&!process.env.DISPLAY,timeout:30000},async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-chat-tabs-'));t.after(()=>rm(dir,{recursive:true,force:true}));const root=fileURLToPath(new URL('../',import.meta.url));
 const source=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Studio}from${JSON.stringify(join(root,'src/Studio.tsx'))};import{GeneralSettingsContext}from${JSON.stringify(join(root,'src/GeneralSettings.tsx'))};import{AppearanceProvider}from${JSON.stringify(join(root,'src/Appearance.tsx'))};import{EditorView}from'@codemirror/view';import${JSON.stringify(join(root,'src/style.css'))};
 window.calls=[];window.drafts={};window.voiceSubscriptions=0;window.terminalCloses=0;const fileDrafts={};const call=async(method,a={})=>{window.calls.push({method,args:a});if(method==='files')return[{name:'a.js',path:'a.js',directory:false}];if(method==='file.read')return{content:'const x = 1;',hash:'initial',canonicalRoot:'/fixture/'+a.sessionId+'/'+(a.laneId||'session')};if(method==='draft.read')return fileDrafts[a.key]||null;if(method==='draft.set'){fileDrafts[a.key]=a.value;return true;}if(method==='draft.remove'){delete fileDrafts[a.key];return true;}if(method==='project.context')return{root:'/fixture',branch:'main'};if(method==='language.diagnostics')return [];if(method==='composer.read')return window.drafts[a.laneId]||{text:'saved-'+a.laneId,images:[],revision:0};if(method==='composer.save'){window.drafts[a.laneId]={...a,revision:a.revision+1};return window.drafts[a.laneId];}if(method==='dictation.probe')return{supported:false};if(method==='terminal.open')return{id:'pty'};if(method==='terminal.read')return{sequence:1,data:'fixture',exited:false};if(method==='terminal.close'){window.terminalCloses++;return true;}return {};};window.rpo={invoke:call,subscribeTerminal:()=>()=>{},subscribeDictation:()=>{window.voiceSubscriptions++;return()=>window.voiceSubscriptions--;}};
 const lane=(id,ownerId='me',provider='codex')=>({id,ownerId,owner:id.toUpperCase(),provider,status:'done',entries:[{id:'entry-'+id,role:'assistant',text:'Answer '+id,at:new Date().toISOString()}],files:[]});const first={id:'s',workspaceId:'w',owner:'Fixture',title:'First',branch:'main',status:'active',description:'',lanes:[lane('a'),lane('b','me','claude'),lane('c','other')],plan:[],comments:[]},second={...first,id:'s2',title:'Second',lanes:[lane('d')]};
 function App(){const[prefs,setPrefs]=useState({openChatsAsEditorTabs:true}),[theme,setTheme]=useState('dark'),[sessionId,setSession]=useState('s'),[role,setRole]=useState('owner'),[removed,setRemoved]=useState(false),[scope,setScope]=useState('fixture'),[revision,setRevision]=useState(0);window.connection=setScope;window.append=()=>{first.lanes[0].entries=[...first.lanes[0].entries,{id:'streamed',role:'assistant',text:'Live streamed entry',at:new Date().toISOString()}];setRevision(v=>v+1);};window.preferences=p=>setPrefs(v=>({...v,...p}));window.theme=setTheme;window.session=setSession;window.role=setRole;window.removeOther=()=>setRemoved(true);const session=sessionId==='s'?{...first,lanes:first.lanes.filter(l=>!removed||l.id!=='c')}:second;const state={me:{id:'me',name:'Fixture',host:false,roles:{w:role}},identity:{audience:scope},sessions:[session],workspaces:[{id:'w',name:'Fixture'}],members:[{id:'me',name:'Fixture',workspaceId:'w',online:true},{id:'other',name:'Other',workspaceId:'w',online:true}],approvals:[],memories:[],local:{name:'Fixture',os:'darwin',providers:[],paths:{w:'/fixture'},sessionPaths:{},lanePaths:{a:'/fixture/a',b:'/fixture/b'},laneOptions:{}}};return <AppearanceProvider value={{theme,collaboratorColors:true}}><GeneralSettingsContext.Provider value={prefs}><Studio key={session.id} session={session} state={state} call={call} notify={()=>{}} onAddLane={()=>{}} onShare={()=>{}} onRepos={()=>{}}/></GeneralSettingsContext.Provider></AppearanceProvider>;}createRoot(document.getElementById('root')).render(<App/>);window.editor=()=>{const el=document.querySelector('.cm-editor');return el?EditorView.findFromDOM(el):null;};`;
 await build({stdin:{contents:source,loader:'tsx',resolveDir:root},outfile:join(dir,'ui.js'),bundle:true,platform:'browser',format:'iife',logLevel:'silent'});await writeFile(join(dir,'index.html'),'<html><head><link rel="stylesheet" href="ui.css"><style>html,body,#root{height:100%;margin:0}#root{display:flex}</style></head><body><div id="root"></div><script src="ui.js"></script></body></html>');
 const verify=async()=>{
  const check=(v,m)=>{if(!v)throw Error(m);},wait=async fn=>{const end=Date.now()+4500;while(!fn()){if(Date.now()>end)throw Error('UI timeout '+fn);await new Promise(r=>setTimeout(r,15));}};
  const member=id=>document.querySelector('[data-chat-open-id="'+id+'"]'),tab=id=>document.querySelector('[data-chat-id="'+id+'"]'),editorChat=()=>document.querySelector('.chat-editor-content .agent-lane'),dockChat=()=>document.querySelector('.lane-container .agent-lane'),input=area=>area.querySelector('.composer textarea'),setText=(el,value)=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));},dockButton=text=>[...document.querySelectorAll('.dock-tabs button')].find(b=>b.textContent.trim()===text);
  await wait(()=>dockChat()&&input(dockChat())?.value==='saved-a');const a=dockChat(),promptA=input(a);setText(promptA,'Draft A');await wait(()=>window.drafts.a?.text==='Draft A');document.querySelector('button[title="a.js"]').click();await wait(()=>window.editor());window.editor().dispatch({changes:{from:0,to:window.editor().state.doc.length,insert:'UNSAVED FILE'}});const editorDOM=window.editor().dom;
  dockButton('终端').click();await wait(()=>document.querySelector('.xterm'));const terminalDOM=document.querySelector('.xterm');dockButton('AGENT').click();const initialReads=window.calls.filter(c=>c.method==='composer.read').length;const voice=window.voiceSubscriptions;
  a.querySelector('[aria-label="在编辑器中打开聊天"]').click();await wait(()=>tab('a')&&editorChat()===a);check(input(a)===promptA&&promptA.value==='Draft A','move remounted or lost composer');check(window.calls.filter(c=>c.method==='composer.read').length===initialReads&&window.voiceSubscriptions===voice,'move resubscribed/reloaded');check(window.editor().dom===editorDOM&&window.editor().state.doc.toString()==='UNSAVED FILE','opening chat lost editor');
  const rootChoice=document.querySelector('[aria-label="本机工作目录"]').value;member('b').click();await wait(()=>tab('b')&&input(editorChat())?.value==='saved-b');const b=editorChat();setText(input(b),'Draft B');member('c').click();await wait(()=>tab('c')&&editorChat()?.textContent.includes('Answer c'));check(!input(editorChat()),'other member has a sender');check(!window.calls.some(c=>c.method.startsWith('composer.')&&c.args.laneId==='c'),'read/wrote other member composer');check(window.voiceSubscriptions===2,'other lane subscribed to voice');
  window.append();await new Promise(requestAnimationFrame);tab('a').click();await wait(()=>editorChat()===a&&a.textContent.includes('Live streamed entry'));check(window.calls.filter(c=>c.method==='composer.read'&&c.args.laneId==='a').length===1,'stream rebuilt Agent view');
  member('b').click();await wait(()=>editorChat()===b);member('b').click();check(document.querySelectorAll('[data-chat-id="b"]').length===1,'duplicate chat tab');check(document.querySelector('[aria-label="本机工作目录"]').value===rootChoice,'chat changed work directory');check(window.editor().dom===editorDOM&&window.editor().state.doc.toString()==='UNSAVED FILE','member change remounted editor');check(input(b).value==='Draft B','tab switch lost draft');
  window.preferences({openChatsAsEditorTabs:false});await new Promise(requestAnimationFrame);check(document.querySelectorAll('[data-chat-id]').length===3&&editorChat()===b,'preference closed tabs');window.theme('light');await wait(()=>document.documentElement.dataset.theme==='light');check(getComputedStyle(document.querySelector('.chat-editor-tabbar')).backgroundColor!=='rgb(21, 21, 21)','tabs did not adopt light theme');
  document.querySelector('[role=tab]:not([data-chat-id])').click();await wait(()=>document.querySelector('.file-selected'));check(getComputedStyle(document.querySelector('.editor-pane')).visibility==='visible','file tab inaccessible');check(window.editor().dom===editorDOM,'file view remounted');
  document.querySelector('[aria-label="关闭 A 的聊天标签"]').click();await wait(()=>!tab('a')&&dockChat()===a);check(input(a).value==='Draft A','closing tag lost chat');a.querySelector('[aria-label="在编辑器中打开聊天"]').click();await wait(()=>tab('a')&&editorChat()===a);check(input(a)===promptA,'explicit reopen while setting off remounted');
  document.querySelector('[aria-label="关闭 A 的聊天标签"]').click();await wait(()=>dockChat()===a);member('a').click();check(!tab('a')&&dockChat()===a,'disabled preference opened new tab');check(window.terminalCloses===0&&document.querySelector('.xterm')===terminalDOM,'tab operation closed/restarted PTY');
  window.role('viewer');await wait(()=>!input(a)&&!input(b));check(!document.querySelector('.watching button'),'viewer can request stop');window.removeOther();await wait(()=>!tab('c'));check(!window.calls.some(c=>/^(run\.|lane\.|dictation.start|providers.run)/.test(c.method)),'view operation dispatched execution');
  window.session('s2');await wait(()=>member('d'));check(!document.querySelector('[data-chat-id]'),'old session tabs leaked');window.session('s');window.role('owner');await wait(()=>dockChat()&&input(dockChat())?.value==='Draft A');check(window.drafts.a.text==='Draft A'&&window.drafts.b.text==='Draft B','session switch lost persisted drafts');dockChat().querySelector('[aria-label="在编辑器中打开聊天"]').click();await wait(()=>tab('a'));window.connection('different-room');await wait(()=>!tab('a'));check(!window.calls.some(c=>/^(run\.|lane\.|dictation.start|providers.run)/.test(c.method)),'connection switch executed');
 };
 await writeFile(join(dir,'run.cjs'),`const{app,BrowserWindow}=require('electron');app.disableHardwareAcceleration();let win;app.whenReady().then(async()=>{win=new BrowserWindow({show:false,width:1400,height:950,webPreferences:{backgroundThrottling:false}});win.webContents.on('console-message',e=>console.log(e.message));await win.loadFile(${JSON.stringify(join(dir,'index.html'))});await win.webContents.executeJavaScript(${JSON.stringify('('+verify.toString()+')()')});win.setSize(700,850);await win.webContents.executeJavaScript(\`(async()=>{const wait=async f=>{const end=Date.now()+3000;while(!f()){if(Date.now()>end)throw Error('narrow layout timeout '+f);await new Promise(r=>setTimeout(r,15));}};document.querySelector('.lane-container [aria-label="在编辑器中打开聊天"]').click();await wait(()=>document.querySelector('.chat-editor-tabbar'));window.preferences({openChatsAsEditorTabs:true});await new Promise(requestAnimationFrame);document.querySelector('[data-chat-open-id="b"]').click();await wait(()=>document.querySelector('[data-chat-id="b"]'));const bar=document.querySelector('.chat-editor-tabbar');bar.scrollLeft=bar.scrollWidth;await new Promise(requestAnimationFrame);const box=bar.getBoundingClientRect(),content=document.querySelector('.chat-editor-content').getBoundingClientRect();if(box.left<0||box.right>innerWidth||content.width<100)throw Error('narrow chat tabs clipped');})()\`);console.log('CHAT_TABS_PASS');win.destroy();app.exit(0);}).catch(e=>{console.error(e);win?.destroy();app.exit(1);});`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const result=await new Promise((resolve,reject)=>{const child=spawn(electron,[join(dir,'run.cjs')],{env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>output+=v);const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error(output));},25000);child.once('exit',code=>{clearTimeout(timer);resolve({code,output});});child.once('error',reject);});assert.equal(result.code,0,result.output);assert.match(result.output,/CHAT_TABS_PASS/);
});
