import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,rename,symlink} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {diffRows,diffRange} from '../core/comment-anchors.mjs';
import {diffPreview,captureDiffReference,openReference} from '../desktop/services/comment-anchors.mjs';
import {captureReference} from '../desktop/services/references.mjs';
import {read} from '../core/local.mjs';
const sha=v=>createHash('sha256').update(v).digest('hex');
async function repo(t){const root=await mkdtemp(join(tmpdir(),'rpo-anchors-'));t.after(()=>rm(root,{recursive:true,force:true}));const git=args=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();git(['init']);git(['config','user.name','Test']);git(['config','user.email','test@example.test']);await writeFile(join(root,'code.txt'),'one\ntwo\nthree\n');git(['add','.']);git(['commit','-m','base']);return {root,git};}
async function capture(root,args){const p=await diffPreview(root,args);return captureDiffReference(root,{...args,expectedRoot:p.canonicalRoot,expectedDiffHash:p.diffHash,hunk:args.hunk??0});}
test('unified diff parser distinguishes metadata, removed/added/context lines and hunk ranges',()=>{const text='diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -4,2 +4,3 @@\n keep\n-old\n+new\n+extra\n\\ No newline at end of file';const rows=diffRows(text);assert.equal(rows[1].left,null);assert.equal(rows[5].left,5);assert.equal(rows[5].right,null);assert.equal(rows[7].right,6);assert.equal(rows[8].right,null);assert.deepEqual({...diffRange(text,{hunk:0,side:'right'}),rows:undefined},{startLine:4,endLine:6,rows:undefined});assert.throws(()=>diffRange(text,{hunk:0,side:'right',startLine:99}));});
test('unstaged left binds index blob, right binds actual disk; old versions survive edits and deletion',async t=>{const {root}=await repo(t);await writeFile(join(root,'code.txt'),'one\nchanged\nthree\n');const left=await capture(root,{path:'code.txt',side:'left',startLine:2});const right=await capture(root,{path:'code.txt',side:'right',startLine:2});assert.equal(left.excerpt,'two');assert.equal(right.excerpt,'changed');assert.ok(left.blob);assert.equal(right.hash,sha('one\nchanged\nthree\n'));await rm(join(root,'code.txt'));const old=await openReference(root,left);assert.equal(old.mode,'historical');assert.match(old.content,/two/);const saved=await openReference(root,right);assert.equal(saved.mode,'excerpt');assert.equal(saved.content,'changed');});
test('staged rename and delete retain correct original-side paths and blobs',async t=>{const {root,git}=await repo(t);await rename(join(root,'code.txt'),join(root,'renamed.txt'));await writeFile(join(root,'renamed.txt'),'one\ntwo\nthree\nfour\n');git(['add','-A']);const right=await capture(root,{path:'renamed.txt',staged:true,side:'right',startLine:4});const left=await capture(root,{path:'renamed.txt',staged:true,side:'left',startLine:3});assert.equal(left.path,'code.txt');assert.equal(right.path,'renamed.txt');git(['commit','-m','rename']);await rm(join(root,'renamed.txt'));git(['add','-A']);const removed=await capture(root,{path:'renamed.txt',staged:true,side:'left'});assert.equal(removed.endLine,4);assert.equal((await openReference(root,removed)).mode,'historical');});
test('stale diff and root mismatch reject; CRLF worktree remains commentable with raw content hash',async t=>{const {root,git}=await repo(t);git(['config','core.autocrlf','true']);await writeFile(join(root,'code.txt'),'one\r\nCRLF\r\nthree\r\n');const anchor=await capture(root,{path:'code.txt',side:'right',startLine:2});assert.equal(anchor.hash,sha('one\r\nCRLF\r\nthree\r\n'));const p=await diffPreview(root,{path:'code.txt'});await writeFile(join(root,'code.txt'),'one\nnewer\nthree\n');await assert.rejects(captureDiffReference(root,{path:'code.txt',side:'right',hunk:0,expectedRoot:p.canonicalRoot,expectedDiffHash:p.diffHash}),/变化/);await assert.rejects(captureDiffReference(root,{path:'code.txt',side:'right',hunk:0,expectedRoot:'/wrong',expectedDiffHash:p.diffHash}),/目录/);});
test('untracked and exact path handling never silently trim to another file',async t=>{const {root}=await repo(t);await writeFile(join(root,'new.txt'),'new\n');await writeFile(join(root,' new.txt'),'new\n');const anchor=await capture(root,{path:'new.txt',side:'right',startLine:1});assert.equal(anchor.path,'new.txt');assert.equal(anchor.excerpt,'new');await assert.rejects(capture(root,{path:' new.txt',side:'right',startLine:1}),/规范化/);await assert.rejects(capture(root,{path:'new.txt',side:'left'}),/没有/);});
test('file anchors show only exact matching current content or saved original excerpt',async t=>{const {root}=await repo(t);const disk=await read(root,'code.txt');const a=await captureReference(root,{path:'code.txt',startLine:2,endLine:2,expectedHash:disk.hash});assert.equal((await openReference(root,a)).mode,'current');await writeFile(join(root,'code.txt'),'wrong\nreplacement\n');assert.equal((await openReference(root,a)).mode,'historical');const b={...a,hash:'f'.repeat(64),commit:'f'.repeat(40),excerpt:'saved'};assert.equal((await openReference(root,b)).mode,'excerpt');delete b.excerpt;assert.equal((await openReference(root,b)).mode,'unavailable');await assert.rejects(openReference(root,{...a,path:'../outside'}));});

test('worktree symbolic links cannot masquerade as regular diff lines',{skip:process.platform==='win32'},async t=>{const {root}=await repo(t);await writeFile(join(root,'target.txt'),'target.txt');await rm(join(root,'code.txt'));await symlink('target.txt',join(root,'code.txt'));await assert.rejects(capture(root,{path:'code.txt',side:'right',hunk:1}),/符号链接/);});

test('old anchor never follows replacement symlink to another same-content file',{skip:process.platform==='win32'},async t=>{const {root}=await repo(t);const disk=await read(root,'code.txt');const a=await captureReference(root,{path:'code.txt',startLine:1,expectedHash:disk.hash});await writeFile(join(root,'same.txt'),disk.content);await rm(join(root,'code.txt'));await symlink('same.txt',join(root,'code.txt'));assert.equal((await openReference(root,a)).mode,'historical');});
