import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { Hub } from "./helpers/secure-hub.mjs";
import { HubClient } from "../core/client.mjs";
import { createCoordinationMcp } from "../core/mcp-coordination.mjs";
const commitA = "a".repeat(40), commitB = "b".repeat(40);
async function setup(t) {
  const dir = await mkdtemp(join(tmpdir(), "rpo-coordination-"));
  const hub = new Hub(dir);
  const owner = { id: "owner", name: "房主", host: true };
  const w = hub.act(owner, "workspace.create", { name: "协作", branch: "main" });
  const peers = {};
  for (const role of ["viewer", "commenter", "editor", "owner"]) {
    const p = { id: role + "-guest", name: role, host: false, workspaceId: w.id };
    hub.registerMember(p, w.id, role); peers[role] = p;
  }
  const s = hub.act(owner, "session.create", { workspaceId: w.id, title: "认证页面" });
  const act = (peer, method, args = {}) => hub.act(peer, method, { workspaceId: w.id, sessionId: s.id, ...args });
  const lane = act(peers.editor, "lane.create", { provider: "codex" });
  t.after(async () => { await hub.close(); await rm(dir, { recursive: true, force: true }); });
  return { hub, owner, w, s, peers, act, lane, dir };
}
test("role matrix enforces read/comment/edit/owner on server without trusting supplied role", async t => {
  const { act, peers, owner, w, hub, s, lane } = await setup(t);
  assert.equal(act(peers.viewer, "session.export").id, s.id);
  for (const method of [ "lane.create", "memory.add", "run.request", "lock.acquire", "coordination.message", "snapshot.publish"]) {
    assert.throws(() => act(peers.viewer, method, { text: "test", title: "test", laneId: lane.id, role: "owner" }), /editor 权限/);
    assert.throws(() => act(peers.commenter, method), /editor 权限/);
  }
  assert.throws(() => act(peers.viewer, "plan.add", { text: "test" }), /commenter 权限/);
  assert.throws(() => act(peers.viewer, "comment.add", { text: "no" }), /commenter 权限/);
  const c = act(peers.commenter, "comment.add", { text: "comment" });
  assert.equal(act(peers.commenter, "comment.resolve", { id: c.id }).status, "resolved");
  assert.throws(() => act(peers.editor, "invite.create"), /owner 权限/);
  const invite = act(peers.owner, "invite.create", { role: "viewer" });
  assert.equal(invite.role, "viewer");
  assert.throws(() => act(peers.owner, "invite.create", { role: "superadmin" }), /未知成员角色/);
  assert.equal(hub.snapshot(owner).me.roles[w.id], "owner");
  assert.equal(hub.snapshot(peers.viewer).me.roles[w.id], "viewer");
});
test("member demotion fences running events, pending claims and file locks", async t => {
  const { act, peers, owner, lane, hub } = await setup(t);
  const ap = act(peers.editor, "run.request", { laneId: lane.id, prompt: "实现登录", mode: "workspace-write" });
  act(owner, "approval.decide", { id: ap.id, allow: true });
  act(peers.editor, "run.claim", { id: ap.id });
  act(peers.editor, "lock.acquire", { laneId: lane.id, path: "auth.ts" });
  act(owner, "member.role", { memberId: peers.editor.id, role: "viewer" });
  assert.equal(lane.status, "interrupted");
  assert.equal(hub.db.locks.length, 0);
  assert.throws(() => act(peers.editor, "run.entry", { laneId: lane.id, runId: ap.id, role: "assistant", text: "bypass" }), /editor 权限/);
  assert.throws(() => act(owner, "member.role", { memberId: owner.id, role: "viewer" }), /房主角色/);
});
test("plans support atomic claim, assignment, transfer and consistent legacy toggle", async t => {
  const { act, peers, owner } = await setup(t);
  const p = act(owner, "plan.add", { text: "认证改造" });
  act(peers.editor, "plan.claim", { id: p.id });
  assert.equal(p.assigneeId, peers.editor.id);
  assert.equal(p.status, "in-progress");
  assert.throws(() => act(peers.owner, "plan.claim", { id: p.id }), /已由其他/);
  act(peers.editor, "plan.transfer", { id: p.id, assigneeId: peers.owner.id });
  assert.equal(p.assigneeId, peers.editor.id);
  act(peers.owner, "plan.transfer.accept", { id: p.id });
  assert.equal(p.assigneeId, peers.owner.id);
  assert.throws(() => act(peers.editor, "plan.transfer", { id: p.id, assigneeId: peers.editor.id }), /只有负责人/);
  assert.throws(() => act(peers.editor, "plan.assign", { id: p.id, assigneeId: peers.editor.id }), /只有负责人/);
  assert.throws(() => act(owner, "plan.assign", { id: p.id, assigneeId: peers.viewer.id }), /Commenter/);
  act(owner, "plan.status", { id: p.id, status: "done" });
  assert.equal(p.done, true);
  act(owner, "plan.toggle", { id: p.id });
  assert.equal(p.status, "todo"); assert.equal(p.done, false);
  assert.ok(p.history.some(h => h.action === "transfer-accepted"));
});
test("code comments keep exact anchors, detect changed commits, and convert once into approved workflow", async t => {
  const { act, peers, owner, lane, s } = await setup(t);
  const c = act(peers.commenter, "comment.add", { text: "修复认证过期", location: { path: "src/auth.ts", startLine: 10, endLine: 13, commit: commitA, side: "right" } });
  assert.equal(c.anchor, "src/auth.ts:10-13");
  act(owner, "comment.check", { files: [{ path: "src/auth.ts", commit: commitB }] });
  assert.equal(c.stale, true);
  assert.throws(() => act(peers.commenter, "comment.task", { id: c.id }), /editor 权限/);
  const result = act(peers.editor, "comment.task", { id: c.id, laneId: lane.id, mode: "read-only" });
  assert.equal(result.plan.commentId, c.id); assert.equal(c.taskId, result.plan.id);
  assert.equal(result.approval.status, "pending");
  assert.equal(result.approval.files[0], "src/auth.ts");
  assert.throws(() => act(peers.editor, "comment.task", { id: c.id }), /已转为/);
  assert.equal(s.plan.length, 1);
  for (const loc of [{ path: "../secret", startLine: 1, commit: commitA }, { path: "a", startLine: 5, endLine: 3, commit: commitA }, { path: "a", startLine: 1, commit: "HEAD" }]) assert.throws(() => act(owner, "comment.add", { text: "bad", location: loc }));
});
test("failed comment-to-run conversion leaves no partial plan or comment linkage", async t => {
  const { act, owner, lane, s } = await setup(t);
  const c = act(owner, "comment.add", { text: "测试" });
  assert.throws(() => act(owner, "comment.task", { id: c.id, laneId: lane.id }), /自己的/);
  assert.equal(s.plan.length, 0); assert.equal(c.taskId, undefined);
});
test("memory staleness respects per-file content and survives partial checks and text-only updates", async t => {
  const { act, owner } = await setup(t);
  const m = act(owner, "memory.add", { title: "认证规则", text: "返回401", files: [{ path: "auth.ts", commit: commitA, hash: commitA }, { path: "token.ts", commit: commitA }] });
  act(owner, "memory.check", { files: [{ path: "auth.ts", commit: commitB, hash: commitA }] });
  assert.equal(m.stale, false);
  act(owner, "memory.check", { files: [{ path: "auth.ts", commit: commitB, hash: commitB }] });
  assert.equal(m.stale, true);
  act(owner, "memory.check", { files: [{ path: "token.ts", commit: commitA }] });
  assert.equal(m.stale, true);
  act(owner, "memory.update", { id: m.id, text: "需要重新检查" });
  assert.equal(m.stale, true);
  act(owner, "memory.update", { id: m.id, files: [{ path: "auth.ts", commit: commitB, hash: commitB }] });
  assert.equal(m.stale, false);
});
test("file locks detect directory overlaps, expire, require owner and cannot escape workspace", async t => {
  const { act, peers, owner, lane, hub } = await setup(t);
  const hostLane = act(owner, "lane.create", { provider: "claude" });
  const held = act(peers.editor, "lock.acquire", { laneId: lane.id, path: "src", ttlMs: 1000 });
  assert.equal(held.acquired, true);
  const denied = act(owner, "lock.acquire", { laneId: hostLane.id, path: "src/auth.ts" });
  assert.equal(denied.acquired, false); assert.equal(denied.conflicts[0].id, held.lock.id);
  assert.throws(() => act(peers.editor, "lock.acquire", { laneId: lane.id, path: "../secret" }), /路径无效/);
  assert.throws(() => act(peers.editor, "lock.renew", { id: held.lock.id, ttlMs: 99999999 }), /时长/);
  held.lock.expires = Date.now() - 1;
  assert.equal(hub.snapshot(owner).locks.length, 0);
  assert.equal(act(owner, "lock.acquire", { laneId: hostLane.id, path: "src/auth.ts" }).acquired, true);
});
test("overlap warnings explain path prefix, task terms, branch and advisory locks", async t => {
  const { act, peers, owner, lane } = await setup(t);
  const hostLane = act(owner, "lane.create", { provider: "claude" });
  act(peers.editor, "run.request", { laneId: lane.id, prompt: "change login authentication", mode: "workspace-write", files: ["src/auth"] });
  const ap = act(owner, "run.request", { laneId: hostLane.id, prompt: "change login authentication tests", mode: "workspace-write", files: ["src/auth/token.ts"] });
  assert.equal(ap.overlapDetails[0].confidence, "high");
  assert.match(ap.overlapDetails[0].reason, /活动文件/);
  act(owner, "lane.stop", { laneId: hostLane.id });
  const advisory = act(owner, "run.request", { laneId: hostLane.id, prompt: "login authentication validation", mode: "workspace-write", files: [] });
  assert.equal(advisory.overlapDetails[0].confidence, "advisory");
  assert.match(advisory.overlapDetails[0].reason, /main/);
});
test("snapshot metadata binds lane ownership and safe session/owner refs", async t => {
  const { act, peers, owner, lane, s } = await setup(t);
  const ref = `refs/rpo/snapshots/${s.id}/${peers.editor.id}`;
  const snapshot = act(peers.editor, "snapshot.publish", { laneId: lane.id, ref, commit: commitA });
  assert.equal(snapshot.commit, commitA); assert.equal(s.snapshots.length, 1);
  assert.throws(() => act(owner, "snapshot.publish", { laneId: lane.id, ref, commit: commitB }), /自己的/);
  assert.throws(() => act(peers.editor, "snapshot.publish", { laneId: lane.id, ref: "refs/heads/main", commit: commitB }), /引用/);
  assert.throws(() => act(peers.editor, "snapshot.publish", { laneId: lane.id, ref: `refs/rpo/snapshots/other/${peers.editor.id}`, commit: commitB }), /引用/);
  assert.equal(act(peers.viewer, "session.export").snapshots[0].commit, commitA);
  assert.equal(act(peers.editor, "snapshot.status", { laneId: lane.id, status: "conflict", message: "auth.ts" }).status, "conflict");
});
test("scoped messages persist, remain workspace isolated, and are available in live context", async t => {
  const { act, owner, peers, lane, hub, w, dir } = await setup(t);
  act(peers.editor, "coordination.message", { laneId: lane.id, text: "认证接口已完成" });
  const other = hub.act(owner, "workspace.create", { name: "其他" });
  const otherSession = hub.act(owner, "session.create", { workspaceId: other.id, title: "private" });
  hub.act(owner, "coordination.message", { sessionId: otherSession.id, text: "不可见" });
  assert.equal(hub.snapshot(peers.viewer).messages.length, 1);
  assert.equal(act(peers.viewer, "coordination.context").messages[0].text, "认证接口已完成");
  hub.save(); const restored = new Hub(dir);
  assert.equal(restored.db.messages.length, 2);
  assert.equal(restored.db.members.find(m => m.id === peers.viewer.id && m.workspaceId === w.id).role, "viewer");
});
test("removed member cannot reconnect using previous or new invite; downgraded role survives reauth", async t => {
  const { hub, owner, w } = await setup(t);
  await hub.listen();
  const auth = { token: hub.act(owner, "invite.create", { workspaceId: w.id, role: "editor" }).token, secret: randomBytes(32).toString("hex"), name: "Remote" };
  const client = new HubClient(); t.after(() => client.close());
  const state = await client.connect(`ws://127.0.0.1:${hub.port}`, auth);
  hub.act(owner, "member.role", { workspaceId: w.id, memberId: state.me.id, role: "viewer" });
  client.close();
  assert.equal((await client.connect(`ws://127.0.0.1:${hub.port}`, auth)).me.role, "viewer");
  hub.act(owner, "member.remove", { workspaceId: w.id, memberId: state.me.id });
  client.close();
  auth.token = hub.act(owner, "invite.create", { workspaceId: w.id, role: "owner" }).token;
  await assert.rejects(client.connect(`ws://127.0.0.1:${hub.port}`, auth), /移除/);
});
test("legacy hub migrates host ownership on authentication and legacy invites default to editor", async t => {
  const { hub, w, dir } = await setup(t);
  const legacy = { ...hub.db }; delete legacy.members; delete legacy.locks; delete legacy.messages;
  legacy.invites = [{ id: "old", workspaceId: w.id, token: "legacy-token", expires: Date.now() + 60000 }];
  await writeFile(join(dir, "legacy.json"), JSON.stringify(legacy));
  const legacyDir = await mkdtemp(join(tmpdir(), "rpo-migration-"));
  await writeFile(join(legacyDir, "hub.json"), JSON.stringify(legacy));
  const migrated = new Hub(legacyDir); await migrated.listen();
  const host = new HubClient(), guest = new HubClient();
  t.after(async () => { host.close(); guest.close(); await migrated.close(); await rm(legacyDir, { recursive: true, force: true }); });
  const hostState = await host.connect(`ws://127.0.0.1:${migrated.port}`, { token: legacy.hostToken, secret: randomBytes(32).toString("hex"), name: "Host" });
  assert.equal(hostState.me.roles[w.id], "owner");
  const guestState = await guest.connect(`ws://127.0.0.1:${migrated.port}`, { token: "legacy-token", secret: randomBytes(32).toString("hex"), name: "Old guest" });
  assert.equal(guestState.me.roles[w.id], "editor");
});
test("MCP tools preserve scope and perform real Hub role authorization", async t => {
  const { act, peers, s, lane } = await setup(t);
  const dispatch = createCoordinationMcp({ client: { call: (m, a) => act(peers.editor, m, a) }, sessionId: s.id, laneId: lane.id });
  const call = (method, params) => dispatch({ jsonrpc: "2.0", id: 1, method, params });
  assert.equal((await call("tools/list")).error.code, -32000);
  assert.equal((await call("initialize", {})).result.protocolVersion, "2025-06-18");
  assert.equal((await call("tools/list")).result.tools.length, 10);
  assert.equal((await call("tools/call", { name: "rpo_plan_add", arguments: { text: "测试", sessionId: "other" } })).error.code, -32602);
  const result = await call("tools/call", { name: "rpo_plan_add", arguments: { text: "MCP任务" } });
  assert.equal(result.result.isError, false); assert.equal(s.plan[0].text, "MCP任务");
  const viewer = createCoordinationMcp({ client: { call: (m, a) => act(peers.viewer, m, a) }, sessionId: s.id });
  await viewer({ jsonrpc: "2.0", id: 1, method: "initialize" });
  const denied = await viewer({ jsonrpc: "2.0", id: 2, method: "tools/call", params: { name: "rpo_plan_add", arguments: { text: "denied" } } });
  assert.equal(denied.result.isError, true); assert.match(denied.result.content[0].text, /commenter 权限/);
});
test("stdio MCP subprocess performs JSON-RPC handshake, list and live claim without leaking config", async t => {
  const { hub, owner, w, s } = await setup(t); await hub.listen();
  const token = hub.act(owner, "invite.create", { workspaceId: w.id }).token;
  const secret = randomBytes(32).toString("hex");
  const proc = spawn(process.execPath, [resolve("core/mcp-coordination.mjs")], { env: { ...process.env, RPO_HUB_URL: `ws://127.0.0.1:${hub.port}`, RPO_HUB_TOKEN: token, RPO_CLIENT_SECRET: secret, RPO_SESSION_ID: s.id } });
  t.after(() => proc.kill());
  const lines = createInterface({ input: proc.stdout }); const requests = new Map(); let allOutput = "";
  proc.stdout.on("data", chunk => { allOutput += chunk; });
  lines.on("line", line => { const message = JSON.parse(line); requests.get(message.id)?.(message); });
  let index = 0;
  const rpc = (method, params) => new Promise((resolve, reject) => {
    const id = ++index; const timer = setTimeout(() => reject(Error("MCP response timed out")), 5000);
    requests.set(id, value => { clearTimeout(timer); resolve(value); });
    proc.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
  });
  assert.equal((await rpc("initialize", { protocolVersion: "2025-06-18" })).result.serverInfo.name, "ready-player-one-coordination");
  assert.ok((await rpc("tools/list")).result.tools.some(t => t.name === "rpo_plan_claim"));
  const add = await rpc("tools/call", { name: "rpo_plan_add", arguments: { text: "从原生CLI拆分" } });
  const plan = JSON.parse(add.result.content[0].text);
  const claim = await rpc("tools/call", { name: "rpo_plan_claim", arguments: { id: plan.id } });
  assert.equal(JSON.parse(claim.result.content[0].text).status, "in-progress");
  assert.equal(allOutput.includes(token), false); assert.equal(allOutput.includes(secret), false);
  const exited = new Promise(resolve => proc.once("exit", resolve)); proc.stdin.end(); assert.equal(await exited, 0);
});
test("Commenter can create, claim, block and finish own plans but cannot change another person's work", async t => {
  const { act, peers, owner } = await setup(t);
  const mine = act(peers.commenter, "plan.add", { text: "检查交付物" });
  act(peers.commenter, "plan.claim", { id: mine.id });
  assert.equal(mine.assigneeId, peers.commenter.id);
  act(peers.commenter, "plan.status", { id: mine.id, status: "blocked" });
  act(peers.commenter, "plan.status", { id: mine.id, status: "done" });
  assert.equal(mine.done, true);
  const theirs = act(owner, "plan.add", { text: "其他工作", assigneeId: peers.editor.id });
  assert.throws(() => act(peers.commenter, "plan.status", { id: theirs.id, status: "done" }), /自己负责/);
  assert.throws(() => act(peers.commenter, "plan.add", { text: "越权分配", assigneeId: peers.editor.id }), /自己的计划/);
});
test("in-progress transfer requires current assignee release then recipient acceptance even for Owner", async t => {
  const { act, owner, peers } = await setup(t);
  const p = act(owner, "plan.add", { text: "正在实现" });
  act(peers.editor, "plan.claim", { id: p.id });
  act(owner, "plan.transfer", { id: p.id, assigneeId: peers.commenter.id });
  assert.equal(p.transferRequest.status, "awaiting-release"); assert.equal(p.assigneeId, peers.editor.id);
  assert.throws(() => act(owner, "plan.transfer.accept", { id: p.id }), /当前待确认/);
  assert.throws(() => act(peers.commenter, "plan.transfer.accept", { id: p.id }), /当前待确认/);
  act(peers.editor, "plan.transfer.accept", { id: p.id });
  assert.equal(p.transferRequest.status, "awaiting-accept"); assert.equal(p.assigneeId, peers.editor.id);
  act(peers.commenter, "plan.transfer.accept", { id: p.id });
  assert.equal(p.assigneeId, peers.commenter.id);
  act(peers.commenter, "plan.transfer", { id: p.id, assigneeId: peers.editor.id });
  act(peers.editor, "plan.transfer.decline", { id: p.id });
  assert.equal(p.assigneeId, peers.commenter.id); assert.equal(p.transferRequest.status, "declined");
});
async function running(t) {
  const fixture = await setup(t), { act, peers, owner, lane } = fixture;
  const ap = act(peers.editor, "run.request", { laneId: lane.id, prompt: "实现认证", mode: "workspace-write" });
  act(owner, "approval.decide", { id: ap.id, allow: true });
  act(peers.editor, "run.claim", { id: ap.id });
  return { ...fixture, ap };
}
test("streamed run events are idempotent and export one merged entry with persisted provider session", async t => {
  const { act, peers, owner, lane, ap, hub, dir } = await running(t);
  const event = { laneId: lane.id, runId: ap.id, role: "assistant", entryId: "stream-1", delta: true };
  act(peers.editor, "run.session", { laneId: lane.id, runId: ap.id, providerSessionId: "provider-session-1" });
  act(peers.editor, "run.entry", { ...event, eventId: "e1", text: "你" });
  act(peers.editor, "run.entry", { ...event, eventId: "e2", text: "好" });
  const duplicate = act(peers.editor, "run.entry", { ...event, eventId: "e2", text: "好" });
  assert.equal(duplicate.duplicate, true);
  const entries = act(owner, "session.export").lanes[0].entries.filter(e => e.id === "stream-1");
  assert.equal(entries.length, 1); assert.equal(entries[0].text, "你好");
  assert.throws(() => act(peers.editor, "run.entry", { ...event, eventId: "e3", role: "tool", text: "fake" }), /消息角色/);
  hub.save(); const restored = new Hub(dir);
  assert.equal(restored.db.sessions[0].lanes[0].providerSessionId, "provider-session-1");
  assert.throws(() => act(owner, "run.session", { laneId: lane.id, runId: ap.id, providerSessionId: "fake" }), /自己的/);
});
test("per-tool decisions are editor-only, single consumption, scoped to active owner and fenced on stop", async t => {
  const { act, owner, peers, lane, ap } = await running(t);
  const args = { laneId: lane.id, runId: ap.id, providerRequestId: "native-1", action: "shell", input: { command: "npm test" } };
  const request = act(peers.editor, "tool.request", args);
  const claimKey = "a".repeat(64);
  assert.equal(act(peers.editor, "tool.request", args).id, request.id);
  assert.throws(() => act(peers.viewer, "tool.decide", { id: request.id, allow: true }), /editor 权限/);
  assert.throws(() => act(peers.commenter, "tool.decide", { id: request.id, allow: true }), /editor 权限/);
  assert.throws(() => act(peers.editor, "tool.claim", { id: request.id, claimKey }), /未决定/);
  act(owner, "tool.decide", { id: request.id, allow: true });
  assert.throws(() => act(owner, "tool.decide", { id: request.id, allow: false }), /已经处理/);
  assert.throws(() => act(owner, "tool.claim", { id: request.id, claimKey }), /自己执行/);
  assert.equal(act(peers.editor, "tool.claim", { id: request.id, claimKey }).allowed, true);
  assert.throws(() => act(peers.editor, "tool.claim", { id: request.id, claimKey: "b".repeat(64) }), /已经领取/);
  assert.throws(() => act(peers.editor, "tool.claim", { id: request.id }), /已经领取/);
  const replay = act(peers.editor, "tool.claim", { id: request.id, claimKey });
  assert.equal(replay.allowed, true); assert.equal(replay.status, "consumed");
  const next = act(peers.editor, "tool.request", { ...args, providerRequestId: "native-2" });
  act(owner, "lane.stop", { laneId: lane.id });
  assert.equal(next.status, "cancelled");
  assert.throws(() => act(peers.editor, "tool.claim", { id: request.id, claimKey }), /已结束/);
  assert.throws(() => act(peers.editor, "tool.request", { ...args, providerRequestId: "native-3" }), /已结束/);
});
test("queued prompts require new approval, remain ordered and cannot be claimed concurrently", async t => {
  const { act, peers, owner, lane, ap } = await running(t);
  const q1 = act(peers.editor, "run.queue", { laneId: lane.id, prompt: "第一项", mode: "read-only" });
  const q2 = act(peers.editor, "run.queue", { laneId: lane.id, prompt: "第二项", mode: "read-only" });
  assert.throws(() => act(peers.editor, "run.queue.next", { laneId: lane.id }), /尚未结束/);
  assert.throws(() => act(peers.editor, "run.queue", { laneId: lane.id, prompt: "非法路径", mode: "read-only", files: ["../secret"] }), /路径/);
  act(peers.editor, "run.finish", { laneId: lane.id, runId: ap.id, status: "done" });
  const next = act(peers.editor, "run.queue.next", { laneId: lane.id });
  assert.equal(next.queue.id, q1.id); assert.equal(next.approval.status, "pending");
  assert.throws(() => act(peers.editor, "run.queue.next", { laneId: lane.id }), /尚未结束/);
  act(owner, "approval.decide", { id: next.approval.id, allow: false });
  assert.equal(act(peers.editor, "run.queue.next", { laneId: lane.id }).queue.id, q2.id);
});
test("guidance is owner-only, acknowledged once and never pretends provider delivered unsupported input", async t => {
  const { act, peers, owner, lane, ap } = await running(t);
  assert.throws(() => act(owner, "run.steer", { laneId: lane.id, runId: ap.id, text: "steal" }), /自己的/);
  const args = { laneId: lane.id, runId: ap.id, text: "先跑测试", eventId: "guidance-1" };
  const guide = act(peers.editor, "run.steer", args);
  assert.equal(act(peers.editor, "run.steer", args).id, guide.id);
  act(peers.editor, "run.steer.ack", { laneId: lane.id, runId: ap.id, id: guide.id, status: "unsupported", message: "CLI 不支持" });
  assert.equal(guide.status, "unsupported");
  act(peers.editor, "run.steer.ack", { laneId: lane.id, runId: ap.id, id: guide.id, status: "delivered" });
  assert.equal(guide.status, "unsupported");
});
test("reconciliation resumes same unfinished run only and rejects stopped, replaced or downgraded ownership", async t => {
  const { act, peers, owner, lane, ap, hub, dir } = await running(t);
  act(peers.editor, "run.entry", { laneId: lane.id, runId: ap.id, eventId: "offline-before", role: "assistant", text: "已开始" });
  hub.save(); const restored = new Hub(dir);
  const args = { sessionId: hub.db.sessions[0].id, laneId: lane.id, runId: ap.id };
  assert.equal(restored.db.sessions[0].lanes[0].status, "interrupted");
  assert.deepEqual(restored.act(peers.editor, "run.reconcile", args).acceptedEventIds, ["offline-before"]);
  assert.equal(restored.db.sessions[0].lanes[0].status, "running");
  act(owner, "lane.stop", { laneId: lane.id });
  assert.throws(() => act(peers.editor, "run.reconcile", { laneId: lane.id, runId: ap.id }), /被替代或撤销/);
  const fresh = act(peers.editor, "run.request", { laneId: lane.id, prompt: "新任务", mode: "read-only" });
  act(owner, "approval.decide", { id: fresh.id, allow: true });
  act(peers.editor, "run.claim", { id: fresh.id });
  assert.throws(() => act(peers.editor, "run.reconcile", { laneId: lane.id, runId: ap.id }), /被替代或撤销/);
  act(owner, "member.role", { memberId: peers.editor.id, role: "viewer" });
  assert.throws(() => act(peers.editor, "run.reconcile", { laneId: lane.id, runId: fresh.id }), /editor 权限/);
});
test("real transport disconnect preserves run identity; reconnect reconciles and deduplicates buffered output", async t => {
  const { hub, owner, w, s } = await setup(t); await hub.listen();
  const auth = { token: hub.act(owner, "invite.create", { workspaceId: w.id }).token, secret: randomBytes(32).toString("hex"), name: "离线执行者" };
  const client = new HubClient(); t.after(() => client.close());
  await client.connect(`ws://127.0.0.1:${hub.port}`, auth);
  const lane = await client.call("lane.create", { sessionId: s.id, provider: "codex" });
  const ap = await client.call("run.request", { sessionId: s.id, laneId: lane.id, mode: "read-only", prompt: "检查" });
  hub.act(owner, "approval.decide", { id: ap.id, allow: true });
  await client.call("run.claim", { id: ap.id });
  const event = { sessionId: s.id, laneId: lane.id, runId: ap.id, eventId: "durable-event", role: "assistant", text: "已读取" };
  await client.call("run.entry", event);
  const disconnected = new Promise((resolve, reject) => {
    const timer = setTimeout(() => { hub.off("change", changed); reject(Error("disconnect not observed")); }, 2000);
    const changed = () => { if (hub.db.sessions[0].lanes.at(-1).offlineSince) { clearTimeout(timer); hub.off("change", changed); resolve(); } };
    hub.on("change", changed);
  });
  client.close(); await disconnected;
  const stored = hub.db.sessions[0].lanes.at(-1);
  assert.equal(stored.status, "running"); assert.equal(stored.activeRunId, ap.id);
  await client.connect(`ws://127.0.0.1:${hub.port}`, auth);
  const reconciliation = await client.call("run.reconcile", { sessionId: s.id, laneId: lane.id, runId: ap.id });
  assert.deepEqual(reconciliation.acceptedEventIds, ["durable-event"]);
  assert.equal((await client.call("run.entry", event)).duplicate, true);
  await client.call("run.finish", { sessionId: s.id, laneId: lane.id, runId: ap.id, status: "done" });
  assert.equal(stored.entries.filter(e => e.text === "已读取").length, 1);
  assert.equal(stored.status, "done");
});
test("native question answers are validated before approval and reach owner through one-time claim", async t => {
  const { act, owner, peers, lane, ap } = await running(t);
  const q = act(peers.editor, "tool.request", { laneId: lane.id, runId: ap.id, providerRequestId: "question-1", action: "question", input: { questions: [{ id: "scope" }] } });
  assert.throws(() => act(owner, "tool.decide", { id: q.id, allow: true, answers: { scope: { answers: [123] } } }), /结构/);
  assert.equal(q.status, "pending");
  const answers = { scope: { answers: ["Only current file"] } };
  act(owner, "tool.decide", { id: q.id, allow: true, answers });
  const claimKey = "c".repeat(64);
  const consumed = act(peers.editor, "tool.claim", { id: q.id, claimKey });
  assert.deepEqual(consumed.answers, answers);
  assert.deepEqual(act(peers.editor, "tool.claim", { id: q.id, claimKey }), consumed);
  const shell = act(peers.editor, "tool.request", { laneId: lane.id, runId: ap.id, providerRequestId: "shell-1", action: "shell", input: {} });
  assert.throws(() => act(owner, "tool.decide", { id: shell.id, allow: true, answers }), /结构/);
});
test("elicitation content is accepted only on allowed elicitation and bounded before mutation", async t => {
  const { act, owner, peers, lane, ap } = await running(t);
  const q = act(peers.editor, "tool.request", { laneId: lane.id, runId: ap.id, providerRequestId: "elicit-1", action: "elicitation", input: {} });
  assert.throws(() => act(owner, "tool.decide", { id: q.id, allow: false, content: { region: "CN" } }), /结构/);
  assert.throws(() => act(owner, "tool.decide", { id: q.id, allow: true, content: { value: "x".repeat(100001) } }), /大小/);
  assert.equal(q.status, "pending");
  const content = { region: "CN", enabled: true, count: 2 };
  act(owner, "tool.decide", { id: q.id, allow: true, content });
  assert.deepEqual(act(peers.editor, "tool.claim", { id: q.id }).content, content);
});
test("handoff requires source safe acknowledgement, snapshot sync and single recipient acceptance into fresh native session", async t => {
  const { act, peers, owner, lane, ap, s } = await running(t);
  const target = act(owner, "lane.create", { provider: "claude" }); target.providerSessionId = "old-own-provider-session";
  act(peers.editor, "snapshot.publish", { laneId: lane.id, ref: `refs/rpo/snapshots/${s.id}/${peers.editor.id}`, commit: commitA });
  const h = act(owner, "handoff.request", { laneId: lane.id, targetLaneId: target.id, reason: "接力" });
  assert.equal(lane.status, "running");
  assert.throws(() => act(owner, "handoff.request", { laneId: lane.id, targetLaneId: target.id }), /已有待处理/);
  assert.throws(() => act(owner, "handoff.accept", { id: h.id, syncedCommit: commitA }), /未准备好/);
  assert.throws(() => act(owner, "handoff.ack", { id: h.id, snapshotCommit: commitA }), /原执行者/);
  act(peers.editor, "handoff.ack", { id: h.id, snapshotCommit: commitA, summary: "认证逻辑已完成，继续测试" });
  assert.equal(lane.status, "interrupted"); assert.equal(ap.status, "handed-off");
  assert.throws(() => act(owner, "handoff.accept", { id: h.id, syncedCommit: commitB }), /先同步/);
  assert.throws(() => act(peers.editor, "run.request", { laneId: lane.id, prompt: "继续旧任务", mode: "read-only" }), /等待确认接管/);
  const accepted = act(owner, "handoff.accept", { id: h.id, syncedCommit: commitA });
  assert.equal(accepted.approval.status, "pending"); assert.equal(accepted.approval.ownerId, owner.id);
  assert.equal(target.providerSessionId, undefined); assert.match(accepted.approval.prompt, /新的原生会话/);
  assert.throws(() => act(owner, "handoff.accept", { id: h.id, syncedCommit: commitA }), /已经处理/);
  assert.throws(() => act(peers.editor, "run.reconcile", { laneId: lane.id, runId: ap.id }), /替代或撤销/);
});
test("offline handoff demands explicit incomplete-work acknowledgement and latest source snapshot", async t => {
  const { act, peers, owner, lane, s, hub } = await running(t);
  const target = act(owner, "lane.create", { provider: "codex" });
  act(peers.editor, "snapshot.publish", { laneId: lane.id, ref: `refs/rpo/snapshots/${s.id}/${peers.editor.id}`, commit: commitA });
  const h = act(owner, "handoff.request", { laneId: lane.id, targetLaneId: target.id });
  assert.throws(() => act(owner, "handoff.offline", { id: h.id, snapshotCommit: commitA, acknowledgeUnconfirmedWork: true }), /仍在线/);
  lane.offlineSince = new Date().toISOString();
  assert.throws(() => act(owner, "handoff.offline", { id: h.id, snapshotCommit: commitA }), /明确确认/);
  assert.throws(() => act(owner, "handoff.offline", { id: h.id, snapshotCommit: commitB, acknowledgeUnconfirmedWork: true }), /最近已发布/);
  hub.peers.set({}, peers.editor);
  assert.throws(() => act(owner, "handoff.offline", { id: h.id, snapshotCommit: commitA, acknowledgeUnconfirmedWork: true }), /仍在线/);
  hub.peers.clear();
  act(owner, "handoff.offline", { id: h.id, snapshotCommit: commitA, acknowledgeUnconfirmedWork: true });
  assert.equal(h.checkpoint.offline, true); assert.match(h.checkpoint.summary, /未知/);
});
test("subtask orchestration keeps parent running and requires configured checks before one-time integration", async t => {
  const { act, peers, owner, lane, s } = await running(t);
  const task = act(peers.editor, "subtask.request", { parentLaneId: lane.id, ownerId: owner.id, title: "补测试", prompt: "补认证测试", baseCommit: commitA, requiredCheckIds: ["tests"] });
  assert.equal(lane.status, "running");
  assert.throws(() => act(peers.editor, "subtask.claim", { id: task.id, baseCommit: commitA, worktreeReady: true }), /不属于/);
  assert.throws(() => act(owner, "subtask.claim", { id: task.id, baseCommit: commitB, worktreeReady: true }), /指定快照/);
  const child = act(owner, "subtask.claim", { id: task.id, baseCommit: commitA, worktreeReady: true });
  assert.equal(child.lane.parentLaneId, lane.id); assert.equal(child.approval.status, "pending"); assert.equal(lane.status, "running");
  act(peers.editor, "approval.decide", { id: child.approval.id, allow: true }); act(owner, "run.claim", { id: child.approval.id });
  assert.throws(() => act(owner, "subtask.candidate", { id: task.id, commit: commitB }), /先结束/);
  act(owner, "run.finish", { laneId: child.lane.id, runId: child.approval.id, status: "done" });
  act(owner, "subtask.candidate", { id: task.id, commit: commitB, diff: "+test" });
  assert.throws(() => act(peers.editor, "subtask.integrated", { id: task.id, candidateCommit: commitB, integrationCommit: commitA, checks: [] }), /成功检查/);
  assert.throws(() => act(owner, "subtask.integrated", { id: task.id, candidateCommit: commitB, integrationCommit: commitA, checks: [] }), /父通道/);
  act(peers.editor, "subtask.integrated", { id: task.id, candidateCommit: commitB, integrationCommit: commitA, checks: [{ id: "tests", passed: true, exitCode: 0, commit: commitA }] });
  assert.equal(task.status, "integrated");
  assert.throws(() => act(peers.editor, "subtask.integrated", { id: task.id, candidateCommit: commitB, integrationCommit: commitA, checks: [] }), /已集成/);
  assert.equal(lane.status, "running"); assert.equal(s.lanes.length, 2);
});
test("code anchors use content hash to detect uncommitted edits without unrelated-commit false positives",async t=>{
  const {act,owner}=await setup(t);
  const c=act(owner,"comment.add",{text:"Check this",location:{path:"auth.ts",startLine:2,endLine:4,commit:commitA,hash:"1".repeat(64)}});
  assert.equal(c.location.hash,"1".repeat(64));
  act(owner,"comment.check",{files:[{path:"auth.ts",commit:commitB,hash:"1".repeat(64)}]});assert.equal(c.stale,false);
  act(owner,"comment.check",{files:[{path:"auth.ts",commit:commitA,hash:"2".repeat(64)}]});assert.equal(c.stale,true);
  act(owner,"comment.check",{files:[{path:"auth.ts",commit:"0".repeat(40),hash:"0".repeat(64)}]});assert.equal(c.stale,true);
});

 test("run claim retries require the same persistent key and never duplicate entries or erase acknowledged events", async t => {
  const { act, owner, peers, lane } = await setup(t);
  const ap = act(peers.editor, "run.request", { laneId: lane.id, prompt: "一次执行", mode: "read-only" });
  act(owner, "approval.decide", { id: ap.id, allow: true });
  const claimKey = "f".repeat(64);
  assert.throws(() => act(peers.editor, "run.claim", { id: ap.id, claimKey: "invalid" }), /标识/);
  const initial = act(peers.editor, "run.claim", { id: ap.id, claimKey });
  act(peers.editor, "run.entry", { laneId: lane.id, runId: ap.id, role: "assistant", text: "记录", eventId: "acknowledged" });
  const replay = act(peers.editor, "run.claim", { id: ap.id, claimKey });
  assert.equal(initial.approval.id, replay.approval.id);
  assert.equal(lane.entries.filter(e => e.role === "user").length, 1);
  assert.deepEqual(lane.acceptedEventIds, ["acknowledged"]);
  assert.throws(() => act(peers.editor, "run.claim", { id: ap.id }), /已经领取/);
  assert.throws(() => act(peers.editor, "run.claim", { id: ap.id, claimKey: "e".repeat(64) }), /已经领取/);
  assert.throws(() => act(owner, "run.claim", { id: ap.id, claimKey }), /已经领取/);
  act(owner, "lane.stop", { laneId: lane.id });
  assert.throws(() => act(peers.editor, "run.claim", { id: ap.id, claimKey }), /已经领取/);
});

test("pending guidance closes on finish and stop instead of remaining pending across runs", async t => {
  const {act,peers,owner,lane,ap}=await running(t);
  const first=act(peers.editor,"run.steer",{laneId:lane.id,runId:ap.id,text:"pending first"});
  act(peers.editor,"run.finish",{laneId:lane.id,runId:ap.id,status:"done"});assert.equal(first.status,"failed");assert.equal(first.message,"执行已结束");
  const next=act(peers.editor,"run.request",{laneId:lane.id,prompt:"next",mode:"read-only"});act(owner,"approval.decide",{id:next.id,allow:true});act(peers.editor,"run.claim",{id:next.id});
  const second=act(peers.editor,"run.steer",{laneId:lane.id,runId:next.id,text:"pending second"});
  act(owner,"lane.stop",{laneId:lane.id});assert.equal(second.status,"failed");assert.equal(second.message,"执行已停止");
});
