import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,writeFile,rm,realpath}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{randomBytes,createHash}from'node:crypto';import{Hub}from'./helpers/secure-hub.mjs';import{HubClient}from'../core/client.mjs';import{RunCoordinator}from'../core/run-coordinator.mjs';import{EditPositionPublisher}from'../desktop/services/edit-position-publisher.mjs';
const until=async f=>{const end=Date.now()+5000;while(!await f()){if(Date.now()>end)throw Error('Position pipeline timed out');await new Promise(r=>setTimeout(r,15));}};
test('actual coordinator tool events read disk and reach authorized remote snapshots without executing a provider',async t=>{
 const dir=await realpath(await mkdtemp(join(tmpdir(),'rpo-position-pipeline-'))),hub=new Hub(join(dir,'hub'));await hub.listen();const owner=new HubClient(),viewer=new HubClient();let current=owner;const publisher=new EditPositionPublisher({client:()=>current});let runtimeOptions;
 const runtime={runs:new Map(),async start(options){runtimeOptions=options;this.runs.set(options.runId,{});},async close(){this.runs.clear();}};
 const coordinator=new RunCoordinator({runtime,client:()=>current,dir:join(dir,'outbox'),root:()=>dir,onProviderEvent:(e,c)=>publisher.observe(e,c),onProviderFinish:(id,c)=>publisher.finish(id,c)});
 t.after(async()=>{publisher.dispose();await coordinator.close();owner.close();viewer.close();await hub.close();await rm(dir,{recursive:true,force:true});});
 await owner.connect(`ws://127.0.0.1:${hub.port}`,{token:hub.db.hostToken,secret:randomBytes(32).toString('hex'),name:'Writer'});const w=await owner.call('workspace.create',{name:'Temporary'}),s=await owner.call('session.create',{workspaceId:w.id,title:'Positions'}),l=await owner.call('lane.create',{sessionId:s.id,provider:'claude'}),invite=await owner.call('invite.create',{workspaceId:w.id,sessionId:s.id,role:'viewer'});
 await viewer.connect(`ws://127.0.0.1:${hub.port}`,{token:invite.token,secret:randomBytes(32).toString('hex'),name:'Observer'});const context={workspaceId:w.id,sessionId:s.id,laneId:l.id},a=await owner.call('run.request',{...context,prompt:'fixture',mode:'read-only'});await owner.call('approval.decide',{id:a.id,allow:true});await writeFile(join(dir,'a.txt'),'one\nold\nthree\n');await coordinator.start(a);
 const event={runId:a.id,provider:'claude',type:'tool',itemId:'edit1',phase:'started',item:{type:'tool_use',id:'edit1',name:'Edit',input:{file_path:join(dir,'a.txt'),old_string:'old',new_string:'new'}}};runtimeOptions.onEvent(event);
 const positions=async()=>{const state=await viewer.call('state');return state.sessions[0].lanes[0].editPositions;};await until(async()=>(await positions())?.positions[0]?.phase==='pending');assert.equal((await positions()).positions[0].startLine,2);
 await writeFile(join(dir,'a.txt'),'one\nnew\nthree\n');runtimeOptions.onEvent({...event,phase:'completed',item:{type:'tool_result',tool_use_id:'edit1',content:'ok'}});runtimeOptions.onEnd({status:'done'});
 await until(async()=>(await positions())?.positions[0]?.phase==='completed');assert.equal((await positions()).positions[0].hash,createHash('sha256').update('one\nnew\nthree\n').digest('hex'));
 const before=(await positions()).sequence;current=null;publisher.reset();runtimeOptions.onEvent({...event,itemId:'late',item:{...event.item,id:'late'}});await new Promise(r=>setTimeout(r,30));assert.equal((await positions()).sequence,before,'old connection emitted new markers');
});
