import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{fileURLToPath}from'node:url';import{spawn}from'node:child_process';import{build}from'esbuild';import electron from'electron';
test('real CodeMirror shows exact-version agent marks, clears edits/expiry/revocation and fences remapped projects',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-position-view-')),root=fileURLToPath(new URL('../',import.meta.url));t.after(()=>rm(dir,{recursive:true,force:true}));
 const source=`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{CodeEditor}from'${root}src/CodeEditor';import{AgentEditPositionsContext}from'${root}src/AgentEditPositions';import{EditorSettingsContext}from'${root}src/EditorSettings';import{AppearanceProvider}from'${root}src/Appearance';
 const sha=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),v=>v.toString(16).padStart(2,'0')).join('');
 function App(){const[text,setText]=useState('a\\nb\\nc'),[snapshot,setSnapshot]=useState({local:{online:true},workspaces:[{id:'w'}],sessions:[]}),[binding,setBinding]=useState('original'),[minimap,setMinimap]=useState(true),[theme,setTheme]=useState('dark');Object.assign(window,{text:v=>flushSync(()=>setText(v)),snapshot:v=>flushSync(()=>setSnapshot(v)),binding:v=>flushSync(()=>setBinding(v)),minimap:v=>flushSync(()=>setMinimap(v)),theme:v=>flushSync(()=>setTheme(v))});return <AppearanceProvider value={{theme}}><AgentEditPositionsContext.Provider value={snapshot}><EditorSettingsContext.Provider value={{minimap}}><CodeEditor height='300px' value={text} onChange={setText} onCreateEditor={v=>window.view=v} agentDocument={{workspaceId:'w',path:'a.txt',binding}}/></EditorSettingsContext.Provider></AgentEditPositionsContext.Provider></AppearanceProvider>};createRoot(document.getElementById('root')).render(<App/>);
 const wait=async f=>{const end=Date.now()+5000;while(!f()){if(Date.now()>end)throw Error('UI wait '+f.toString());await new Promise(r=>setTimeout(r,15));}};const check=(v,m)=>{if(!v)throw Error(m);};window.run=async()=>{await wait(()=>window.view);const view=window.view;const hash=await sha('a\\nb\\nc');let sequence=1;const make=(extra={})=>({local:{online:true},workspaces:[{id:'w'}],sessions:[{id:'s',workspaceId:'w',status:'active',lanes:[{id:'l',owner:'Alex',ownerId:'u',activeRunId:'r',status:'running',editPositions:{runId:'r',sequence,expires:Date.now()+60000,positions:[{path:'a.txt',hash,startLine:2,endLine:2,phase:'pending',toolId:'t',source:'claude'}],...extra}}]}]});const canvas=()=>document.querySelector('.rpo-code-minimap');const count=()=>canvas()?.dataset.agentMarkers;
 window.snapshot(make());await wait(()=>count()==='1');check(canvas().title.includes('Alex · 待修改'),'missing phase/identity');window.text('unsaved');await wait(()=>count()==='0');check(window.view===view,'editor remounted');window.text('a\\nb\\nc');await wait(()=>count()==='1');window.binding('different-root');await wait(()=>count()==='0');sequence++;window.snapshot(make());await wait(()=>count()==='1');window.theme('light');await wait(()=>count()==='1');check(window.view===view,'theme remounted editor');window.minimap(false);await wait(()=>!canvas());window.minimap(true);await wait(()=>count()==='1');window.snapshot(make({expires:Date.now()+100}));await wait(()=>count()==='0');sequence++;window.snapshot(make());await wait(()=>count()==='1');window.snapshot({local:{online:true},workspaces:[{id:'w'}],sessions:[]});await wait(()=>count()==='0');check(view.state.doc.toString()==='a\\nb\\nc','marker changes edited document');return true;};`;
 await build({stdin:{contents:source,resolveDir:root,loader:'tsx'},bundle:true,platform:'browser',outfile:join(dir,'ui.js'),jsx:'automatic'});await writeFile(join(dir,'index.html'),'<html><head><link rel="stylesheet" href="ui.css"></head><body><div id="root"></div><script src="ui.js"></script></body></html>');
 await writeFile(join(dir,'run.cjs'),`const{app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(join(dir,'profile'))});app.whenReady().then(async()=>{try{const w=new BrowserWindow({show:false,width:600,height:500,webPreferences:{backgroundThrottling:false}});await w.loadFile(${JSON.stringify(join(dir,'index.html'))});await w.webContents.executeJavaScript('window.run()');console.log('POSITION_VIEW_OK');app.exit(0);}catch(e){console.error(e);app.exit(1);}});setTimeout(()=>app.exit(2),15000);`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(electron,[join(dir,'run.cjs')],{env,stdio:['ignore','pipe','pipe']});const watchdog=setTimeout(()=>child.kill('SIGKILL'),20000);let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);const code=await new Promise((res,rej)=>{child.once('exit',res);child.once('error',rej);});clearTimeout(watchdog);assert.equal(code,0,output);assert.match(output,/POSITION_VIEW_OK/);
});
