import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{randomBytes}from'node:crypto';import{Hub}from'./helpers/secure-hub.mjs';import{HubClient}from'../core/client.mjs';import{visibleEditPositions,validateEditPositions}from'../core/edit-positions.mjs';
const position={path:'src/例子.ts',hash:'a'.repeat(64),startLine:2,endLine:4,phase:'pending',toolId:'tool',source:'codex'};
test('real clients share version-bound edit positions and reject forged owner, scope, replay and revoked writes',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-edit-positions-')),hub=new Hub(dir);await hub.listen();const clients=[];t.after(async()=>{clients.forEach(c=>c.close());await hub.close();await rm(dir,{recursive:true,force:true});});
 const connect=async(token,name)=>{const c=new HubClient();clients.push(c);await c.connect(`ws://127.0.0.1:${hub.port}`,{token,name,secret:randomBytes(32).toString('hex')});return c;};const owner=await connect(hub.db.hostToken,'Host'),w=await owner.call('workspace.create',{name:'Positions'}),s=await owner.call('session.create',{workspaceId:w.id,title:'Visible'}),other=await owner.call('session.create',{workspaceId:w.id,title:'Hidden'});
 const editor=await connect((await owner.call('invite.create',{workspaceId:w.id,sessionId:s.id,role:'editor'})).token,'Writer'),viewer=await connect((await owner.call('invite.create',{workspaceId:w.id,sessionId:s.id,role:'viewer'})).token,'Viewer'),lane=await editor.call('lane.create',{sessionId:s.id,provider:'codex'}),context={workspaceId:w.id,sessionId:s.id,laneId:lane.id};
 const a=await editor.call('run.request',{...context,prompt:'fixture',mode:'read-only'});await owner.call('approval.decide',{id:a.id,allow:true});await editor.call('run.claim',{id:a.id});const batch={...context,runId:a.id,sequence:1,positions:[position]};
 await editor.call('run.editPositions',batch);const state=await viewer.call('state');state.local={online:true};const d={workspaceId:w.id,path:position.path,hash:position.hash};assert.equal(visibleEditPositions(state,d).length,1);assert.equal(state.sessions.some(x=>x.id===other.id),false);
 const remote=state.sessions[0].lanes[0].editPositions;assert.equal(visibleEditPositions(state,d,remote.expires).length,0);assert.equal(visibleEditPositions(state,{...d,hash:'b'.repeat(64)}).length,0);assert.equal(visibleEditPositions({...state,local:{online:false}},d).length,0);assert.equal(visibleEditPositions({...state,sessions:[]},d).length,0);
 await assert.rejects(viewer.call('run.editPositions',batch));await assert.rejects(owner.call('run.editPositions',batch),/自己的/);await assert.rejects(editor.call('run.editPositions',{...batch,sessionId:other.id}),/邀请范围/);
 assert.equal((await editor.call('run.editPositions',batch)).duplicate,true);await assert.rejects(editor.call('run.editPositions',{...batch,positions:[{...position,startLine:1}]}),/内容冲突/);
 await editor.call('run.editPositions',{...batch,sequence:2,positions:[{...position,phase:'completed'}]});assert.equal((await editor.call('run.editPositions',batch)).duplicate,true);
 await editor.call('run.finish',{...context,runId:a.id,status:'done'});await assert.rejects(editor.call('run.editPositions',{...batch,sequence:3}),/状态不匹配/);await editor.call('run.editPositions',{...batch,sequence:3,positions:[{...position,phase:'completed'}]});
 await owner.call('member.role',{workspaceId:w.id,sessionId:s.id,memberId:editor.state.me.id,role:'viewer'});await assert.rejects(editor.call('run.editPositions',{...batch,sequence:4,positions:[]}));
 editor.close();await new Promise(r=>setTimeout(r,30));assert.equal((await viewer.call('state')).sessions[0].lanes[0].editPositions,undefined);
});
test('edit metadata rejects paths, credentials, unbounded ranges, unsupported sources and document contents',()=>{
 for(const patch of [{path:'../x'},{path:'/x'},{path:'C:/x'},{path:'x\\y'},{hash:'bad'},{startLine:0},{endLine:1},{phase:'writing'},{source:'shell'},{content:'private'}])assert.throws(()=>validateEditPositions({sequence:1,positions:[{...position,...patch}]}));
 assert.throws(()=>validateEditPositions({sequence:1,positions:Array(33).fill(position)}));assert.throws(()=>validateEditPositions({sequence:1,positions:[],token:'secret'}));assert.deepEqual(validateEditPositions({sequence:1,positions:[position]}),[position]);
});
