import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{fileURLToPath}from'node:url';import{spawn}from'node:child_process';import{build}from'esbuild';import electron from'electron';
test('real diff controls move without requests, retain comments, fence stale files and obey read-only permissions',{skip:process.platform==='linux'&&!process.env.DISPLAY,timeout:30000},async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-git-review-'));t.after(()=>rm(dir,{recursive:true,force:true}));const root=fileURLToPath(new URL('../',import.meta.url));
 const source=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{GitPanel}from${JSON.stringify(join(root,'src/GitPanel.tsx'))};import{GeneralSettingsContext}from${JSON.stringify(join(root,'src/GeneralSettings.tsx'))};import{AppearanceProvider}from${JSON.stringify(join(root,'src/Appearance.tsx'))};import${JSON.stringify(join(root,'src/style.css'))};
 const file=(path,staged=false)=>({path,staged,unstaged:true,index:staged?'M':' ',worktree:'M',untracked:false,conflict:false});window.calls=[];window.pending={};window.files=[file('a.txt',true),file('b.txt'),file('empty.txt')];const text='diff --git a/a.txt b/a.txt\\n--- a/a.txt\\n+++ b/a.txt\\n@@ -1 +1 @@\\n-old\\n+new\\n';
 const call=async(method,args)=>{window.calls.push({method,args});if(method==='git.status')return{branch:'main',dirty:true,operation:null,conflicts:[],files:window.files};if(method==='git.branches')return{branches:[{name:'main'}],remotes:[]};if(method==='git.diff')return new Promise(resolve=>window.pending[args.path]=()=>resolve({text:args.path==='empty.txt'?'':text+Array.from({length:180},(_,i)=>' context '+i).join('\\n'),diffHash:args.path,canonicalRoot:'/fixture'}));if(method==='git.stage'||method==='git.unstage')return true;if(method==='references.diff')return{path:args.path,commit:'0'.repeat(40)};if(method==='comment.add')return true;throw Error(method);};
 function App(){const[location,setLocation]=useState('breadcrumb'),[theme,setTheme]=useState('dark'),[canWrite,setWrite]=useState(true),[session,setSession]=useState('s');window.configure=(value)=>{if(value.location)setLocation(value.location);if(value.theme)setTheme(value.theme);if(value.canWrite!==undefined)setWrite(value.canWrite);if(value.session)setSession(value.session);};return <AppearanceProvider value={{theme,collaboratorColors:true}}><GeneralSettingsContext.Provider value={{reviewControlLocation:location}}><GitPanel call={call} context={{workspaceId:'w',sessionId:session,laneId:'l'}} canWrite={canWrite} canComment={canWrite}/></GeneralSettingsContext.Provider></AppearanceProvider>;}createRoot(document.getElementById('root')).render(<App/>);`;
 await build({stdin:{contents:source,loader:'tsx',resolveDir:root},outfile:join(dir,'ui.js'),bundle:true,platform:'browser',format:'iife',logLevel:'silent'});await writeFile(join(dir,'index.html'),'<html><head><link rel="stylesheet" href="ui.css"><style>html,body{margin:0;height:100%}#root{width:100%;height:650px}</style></head><body><div id="root"></div><script src="ui.js"></script></body></html>');
 const verify=async()=>{
  const check=(value,message)=>{if(!value)throw Error(message);},wait=async fn=>{const end=Date.now()+4000;while(!fn()){if(Date.now()>end)throw Error('UI timeout '+fn);await new Promise(r=>setTimeout(r,15));}};
  const select=(path,staged=false)=>{const rows=[...document.querySelectorAll('.git-file-group')];rows[staged?0:1].querySelector(`button[title="${path}"]`).click();},controls=()=>document.querySelector('.git-review-controls'),finish=async path=>{await wait(()=>window.pending[path]);window.pending[path]();delete window.pending[path];await wait(()=>controls()||document.querySelector('.git-diff-content')?.textContent.includes('没有文本差异'));};
  await wait(()=>document.querySelectorAll('.git-file-name').length===4);select('a.txt');await finish('a.txt');check(document.querySelectorAll('[aria-label="暂存 a.txt"]').length===1,'duplicate selected-file action');check(controls().closest('.review-breadcrumb'),'default location incorrect');
  document.querySelector('button[title="评论修改后第 1 行"]').click();await wait(()=>document.querySelector('.diff-comment textarea'));const input=document.querySelector('.diff-comment textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(input,'unsent comment');input.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(requestAnimationFrame);
  const previousCalls=window.calls.length,previousControl=controls();window.configure({location:'floating'});await wait(()=>controls()?.closest('.review-floating'));check(window.calls.length===previousCalls,'location switch made an RPC');check(controls()===previousControl,'location remounted controls');check(document.querySelector('.diff-comment textarea')===input&&input.value==='unsent comment','location lost draft');check(getComputedStyle(controls()).position==='sticky','floating control not sticky');
  const dark=getComputedStyle(controls()).backgroundColor;window.configure({theme:'light'});await wait(()=>document.documentElement.dataset.theme==='light');check(getComputedStyle(controls()).backgroundColor!==dark,'floating theme did not change');const bounds=controls().getBoundingClientRect();check(bounds.left>=0&&bounds.right<=innerWidth,'narrow viewport clipped controls');const scroller=document.querySelector('.git-review-body');scroller.scrollTop=250;await new Promise(requestAnimationFrame);const floating=controls().getBoundingClientRect(),scrollBounds=scroller.getBoundingClientRect();check(floating.top>=scrollBounds.top&&floating.bottom<=scrollBounds.bottom,'floating controls scrolled out of review viewport');
  const stageButton=controls().querySelector('button');stageButton.click();stageButton.click();await wait(()=>window.calls.some(c=>c.method==='git.stage'));const stage=window.calls.filter(c=>c.method==='git.stage');check(stage.length===1&&JSON.stringify(stage[0].args)==='{"workspaceId":"w","sessionId":"s","laneId":"l","paths":["a.txt"]}','stage targets wrong context');await wait(()=>!controls());
  select('a.txt',true);await finish('a.txt');check(controls().textContent.includes('取消暂存'),'staged scope incorrect');controls().querySelector('button').click();await wait(()=>window.calls.some(c=>c.method==='git.unstage'));await wait(()=>!controls());
  select('a.txt');await wait(()=>window.pending['a.txt']);select('b.txt');await wait(()=>window.pending['b.txt']);window.pending['a.txt']();delete window.pending['a.txt'];await new Promise(requestAnimationFrame);check(!controls(),'stale preview enabled new-file action');await finish('b.txt');check(controls().querySelector('button').getAttribute('aria-label')==='暂存 b.txt','new-file action not bound');
  select('empty.txt');await finish('empty.txt');check(!controls(),'empty diff has action');check(!!document.querySelector('[aria-label="暂存 empty.txt"]'),'empty file lost original stage action');select('b.txt');await finish('b.txt');const count=window.calls.length;window.configure({canWrite:false});await wait(()=>!controls());check(!document.querySelector('[aria-label="暂存 b.txt"]'),'readonly file action visible');check([...document.querySelectorAll('.git-toolbar select,.git-network button,.git-commit button')].every(el=>el.disabled),'readonly write controls enabled');check(window.calls.length===count,'role change executed a write');
  window.configure({session:'next',canWrite:true});await wait(()=>!document.querySelector('.git-diff'));check(!controls(),'old-session controls remained');check(window.calls.filter(c=>c.method==='git.stage'||c.method==='git.unstage').length===2,'unexpected Git mutation');
 };
 await writeFile(join(dir,'run.cjs'),`const{app,BrowserWindow}=require('electron');app.disableHardwareAcceleration();let win;app.whenReady().then(async()=>{win=new BrowserWindow({show:false,width:380,height:720,webPreferences:{backgroundThrottling:false}});await win.loadFile(${JSON.stringify(join(dir,'index.html'))});await win.webContents.executeJavaScript(${JSON.stringify('('+verify.toString()+')()')});console.log('GIT_REVIEW_PASS');win.destroy();app.exit(0);}).catch(e=>{console.error(e);win?.destroy();app.exit(1);});`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const result=await new Promise((resolve,reject)=>{const child=spawn(electron,[join(dir,'run.cjs')],{env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>output+=v);const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error(output));},25000);child.once('exit',code=>{clearTimeout(timer);resolve({code,output});});child.once('error',reject);});assert.equal(result.code,0,result.output);assert.match(result.output,/GIT_REVIEW_PASS/);
});
