import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{randomBytes}from'node:crypto';import{execFile}from'node:child_process';import{promisify}from'node:util';
import{Hub}from'./helpers/secure-hub.mjs';import{HubClient}from'../core/client.mjs';import{GitService}from'../desktop/services/git.mjs';import{authorizeGit}from'../desktop/services/git-access.mjs';const exec=promisify(execFile);
test('real Hub roles and revocation gate actual Git index writes and scope injection',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-git-access-')),hub=new Hub(join(dir,'hub'));await hub.listen();const clients=[];t.after(async()=>{clients.forEach(c=>c.close());await hub.close();await rm(dir,{recursive:true,force:true});});
 const connect=async token=>{const c=new HubClient();clients.push(c);await c.connect(`ws://127.0.0.1:${hub.port}`,{token,secret:randomBytes(32).toString('hex'),name:'Fixture'});return c;};const owner=await connect(hub.db.hostToken),w=await owner.call('workspace.create',{name:'One'}),w2=await owner.call('workspace.create',{name:'Two'}),s=await owner.call('session.create',{workspaceId:w.id,title:'One'}),s2=await owner.call('session.create',{workspaceId:w2.id,title:'Two'}),lane=await owner.call('lane.create',{sessionId:s.id,provider:'codex'});
 await exec('git',['init',dir]);await writeFile(join(dir,'a.txt'),'fixture');const git=new GitService(),args={workspaceId:w.id,sessionId:s.id,paths:['a.txt']};
 const invoke=async(c,method,a=args)=>{await authorizeGit({method,args:a,client:c,online:()=>true,currentClient:()=>c});return git[method.slice(4)](dir,a);};
 for(const role of ['viewer','commenter']){const invite=await owner.call('invite.create',{workspaceId:w.id,role}),guest=await connect(invite.token);await assert.rejects(invoke(guest,'git.stage'),/Editor/);assert.equal((await git.status(dir)).files.find(f=>f.path==='a.txt').staged,false);await invoke(guest,'git.status',{workspaceId:w.id,sessionId:s.id});}
 const invite=await owner.call('invite.create',{workspaceId:w.id,sessionId:s.id,role:'editor'}),editor=await connect(invite.token);await invoke(editor,'git.stage');assert.equal((await git.status(dir)).files.find(f=>f.path==='a.txt').staged,true);await invoke(editor,'git.unstage');
 await assert.rejects(invoke(editor,'git.stage',{...args,sessionId:s2.id}),/无权/);await assert.rejects(invoke(editor,'git.stage',{...args,workspaceId:w2.id}),/无权/);await assert.rejects(invoke(editor,'git.stage',{...args,laneId:lane.id}),/本机 Agent/);
 for(const injected of [{root:dir},{role:'owner'},{command:'status'},{env:{GIT_DIR:dir}},{extra:true}])await assert.rejects(invoke(editor,'git.stage',{...args,...injected}),/参数/);
 await assert.rejects(invoke(editor,'git.command'),/不支持/);await assert.rejects(invoke(editor,'git.constructor'),/不支持/);
 await owner.call('member.role',{workspaceId:w.id,sessionId:s.id,memberId:editor.state.me.id,role:'viewer'});await assert.rejects(invoke(editor,'git.stage'),/Editor/);assert.equal((await git.status(dir)).files.find(f=>f.path==='a.txt').staged,false);
 await invoke(owner,'git.stage',{...args,laneId:lane.id});assert.equal((await git.status(dir)).files.find(f=>f.path==='a.txt').staged,true);await invoke(owner,'git.unstage');
 await assert.rejects(authorizeGit({method:'git.stage',args,client:owner,online:()=>false,currentClient:()=>owner}),/连接/);
 await assert.rejects(authorizeGit({method:'git.stage',args,client:owner,online:()=>true,currentClient:()=>editor}),/连接已变化/);
 await owner.call('member.remove',{workspaceId:w.id,sessionId:s.id,memberId:editor.state.me.id});await assert.rejects(invoke(editor,'git.stage'));assert.equal((await git.status(dir)).files.find(f=>f.path==='a.txt').staged,false);
});
