import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {spawn} from 'node:child_process';import{build}from'esbuild';import electron from'electron';
test('startup UI ignores late snapshots and restores once; user navigation, disabled setting and revoked access fence responses',{skip:process.platform==='linux'&&!process.env.DISPLAY,timeout:30000},async t=>{
 const dir=await mkdtemp(join(tmpdir(),'rpo-navigation-view-'));t.after(()=>rm(dir,{recursive:true,force:true}));const root=fileURLToPath(new URL('../',import.meta.url));
 const source=`window.calls=[];window.rpo={subscribe:cb=>{window.publish=cb;return()=>{};},invoke:async(method,args)=>{window.calls.push({method,args});if(method==='bootstrap')return new Promise(resolve=>window.boot=resolve);if(method==='navigation.restore')return new Promise(resolve=>window.restore=resolve);return{};},subscribeTerminal:()=>()=>{},subscribeDictation:()=>()=>{},subscribeBrowser:()=>()=>{}};import(${JSON.stringify(join(root,'src/main.tsx'))});`;
 await build({stdin:{contents:source,loader:'tsx',resolveDir:root},outfile:join(dir,'ui.js'),bundle:true,platform:'browser',format:'iife',logLevel:'silent'});await writeFile(join(dir,'index.html'),'<html><head><link rel="stylesheet" href="ui.css"></head><body><div id="root"></div><script src="ui.js"></script></body></html>');
 const verify=async(mode)=>{
  const check=(ok,msg)=>{if(!ok)throw Error(msg);};const wait=async fn=>{const end=Date.now()+4000;while(!fn()){if(Date.now()>end)throw Error('UI timeout '+fn.toString());await new Promise(r=>setTimeout(r,15));}};
  const session=id=>({id,workspaceId:'w',title:id,owner:'Fixture',at:new Date().toISOString(),description:'',branch:'main',status:'active',lanes:[],plan:[],comments:[],files:[],diff:''});
  const state=(revision,overrides={})=>({workspaces:[{id:'w',name:'Fixture'}],sessions:[session('first'),session('last')],memories:[],approvals:[],members:[],me:{id:'me',name:'Fixture',roles:{w:'owner'}},local:{paths:{},sessionPaths:{},providers:[],accounts:[],online:true,dataDir:'/synthetic',name:'Fixture',generalSettings:{restoreLastSession:mode!=='disabled'},navigation:{scope:'scope',epoch:0,ready:true,revision}},...overrides});
  await wait(()=>window.boot&&window.publish);window.publish(state(2));await wait(()=>document.querySelector('.app-shell'));
  if(mode==='disabled'){window.boot(state(1));await new Promise(requestAnimationFrame);check(!window.restore&&!document.querySelector('.studio'),'disabled preference restored');return;}
  await wait(()=>window.restore);window.boot(state(1,{sessions:[]}));await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);
  check([...document.querySelectorAll('.mini-session')].some(el=>el.textContent==='last'),'old bootstrap replaced latest snapshot');
  if(mode==='none'){window.restore(null);await new Promise(requestAnimationFrame);check(!document.querySelector('.studio'),'empty memory jumped into session');}
  else if(mode==='identity'){const changed=state(3);changed.local.navigation.scope='different-identity';changed.me.id='other';window.publish(changed);await new Promise(requestAnimationFrame);window.restore({scope:'scope',workspaceId:'w',sessionId:'last'});await new Promise(requestAnimationFrame);check(!document.querySelector('.studio'),'old identity response restored another identity session');}
  else if(mode==='manual'){[...document.querySelectorAll('.mini-session')].find(el=>el.textContent==='first').click();await wait(()=>document.querySelector('.session-topbar strong')?.textContent==='first');window.restore({scope:'scope',workspaceId:'w',sessionId:'last'});await new Promise(requestAnimationFrame);check(document.querySelector('.session-topbar strong').textContent==='first','restore overrode user navigation');}
  else {window.restore({scope:'scope',workspaceId:'w',sessionId:'last'});await wait(()=>document.querySelector('.session-topbar strong')?.textContent==='last');window.publish(state(3,{sessions:[]}));await wait(()=>!document.querySelector('.studio'));window.publish(state(4));await new Promise(requestAnimationFrame);check(!document.querySelector('.studio'),'permission regain unexpectedly restored again');}
  check(window.calls.filter(c=>c.method==='navigation.restore').length===1,'restore repeated');check(!window.calls.some(c=>/^(run\.|lane\.|handoff\.|terminal\.|providers\.)/.test(c.method)),'restoration invoked execution API');
 };
 await writeFile(join(dir,'run.cjs'),`const{app,BrowserWindow}=require('electron');app.disableHardwareAcceleration();let w;app.whenReady().then(async()=>{w=new BrowserWindow({show:false,webPreferences:{backgroundThrottling:false}});w.webContents.on('console-message',event=>console.log(event.message));for(const mode of ['none','restore','manual','identity','disabled']){await w.loadFile(${JSON.stringify(join(dir,'index.html'))});await w.webContents.executeJavaScript('('+${JSON.stringify(verify.toString())}+')('+JSON.stringify(mode)+')');}console.log('NAVIGATION_VIEW_PASS');w.destroy();app.exit(0);}).catch(e=>{console.error(e);w?.destroy();app.exit(1);});`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const result=await new Promise((resolve,reject)=>{const child=spawn(electron,[join(dir,'run.cjs')],{env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',x=>output+=x);child.stderr.on('data',x=>output+=x);const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error(output));},25000);child.once('exit',code=>{clearTimeout(timer);resolve({code,output});});child.once('error',reject);});assert.equal(result.code,0,result.output);assert.match(result.output,/NAVIGATION_VIEW_PASS/);
});
