import {useEffect,useState} from 'react';
import type {State} from './types';
import type {Call} from './ui';
import {ProviderControls} from './ProviderControls';
export function AgentSettings({state,agentId,call,onOpenSession}:{state:State;agentId:string;call:Call;onOpenSession?:(id:string)=>void}){
 const agent=state.collaboration!.agents.find(a=>a.id===agentId)!;
 const [external,setExternal]=useState<{command?:string;mcp?:unknown;enabled?:boolean;connected?:boolean;expiresAt?:string}|null>(null),[tools,setTools]=useState(''),[tab,setTab]=useState('身份'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const [templateId,setTemplateId]=useState('');
 const [name,setName]=useState(agent.name),[role,setRole]=useState(agent.role),[avatar,setAvatar]=useState(agent.avatar||'🤖'),[memory,setMemory]=useState(agent.memory||''),[provider,setProvider]=useState(agent.provider);
 const lane=state.sessions.find(s=>s.id===agent.sessionId)?.lanes.find(l=>l.id===agent.sourceLaneId);
 const [selection,setSelection]=useState({model:lane?.configuration?.model||'',effort:lane?.configuration?.effort||''});
 const [trigger,setTrigger]=useState(agent.policy?.trigger||'manual'),[autoTasks,setAutoTasks]=useState(agent.policy?.autoTasks||false),[limit,setLimit]=useState(agent.policy?.maxTurnsPerHour||20),[projectIds,setProjectIds]=useState(agent.policy?.projectIds||[agent.projectId||'']);
 const [title,setTitle]=useState(''),[dueAt,setDueAt]=useState(''),[interval,setInterval]=useState(0);
 useEffect(()=>{setProvider(agent.provider);setSelection({model:lane?.configuration?.model||'',effort:lane?.configuration?.effort||''});},[agent.sourceLaneId]);
 const mine=agent.workerId===state.me?.id;
 if(!mine)return null;
 async function run(f:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setSaved('');try{await f();setSaved('已保存');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const life=(action:string)=>void run(()=>call('collab.agent.lifecycle',{agentId,action,provider}));
 const config=(extra:Record<string,unknown>)=>call('collab.agent.configure',{agentId,revision:agent.revision||0,...extra});
 const projects=state.collaboration!.projects.filter(p=>p.teamId===agent.teamId);
 const events=state.collaboration?.agentEvents?.filter(e=>e.agentId===agentId).slice(-20).reverse()||[];
 return <section className="agent-settings"><nav aria-label="Agent 配置">{['身份','运行','协作','记忆','提醒','工具','活动'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='身份'&&<div className="room-form"><label>头像<input maxLength={16} value={avatar} onChange={e=>setAvatar(e.target.value)}/></label><label>名称<input aria-label="修改 Agent 名称" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>角色模板<select defaultValue="" onChange={e=>{setTemplateId(e.target.value);const t=state.collaboration?.roleTemplates?.find(t=>t.id===e.target.value);if(t){setName(t.name);setRole(t.role);}}}><option value="">选择模板（可修改）</option>{state.collaboration?.roleTemplates?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>职责<textarea aria-label="修改 Agent 职责" value={role} maxLength={3000} onChange={e=>setRole(e.target.value)}/></label><div className="room-actions"><button className="button primary" disabled={busy} onClick={()=>void run(()=>config({name,role,avatar}))}>保存</button><button className="button" disabled={busy} onClick={()=>void run(()=>call('collab.template.save',{teamId:agent.teamId,name,role}))}>另存为角色模板</button>{state.collaboration?.roleTemplates?.find(t=>t.id===templateId)?.teamId&&<button className="button" disabled={busy} onClick={()=>void run(()=>call('collab.template.save',{teamId:agent.teamId,id:templateId,name,role}))}>更新此模板</button>}</div></div>}
 {tab==='运行'&&<div className="room-form"><p>{agent.paused?'已暂停':lane?.status==='running'?'正在执行':'已就绪'} · {state.collaboration?.computers?.find(c=>c.id===agent.computerId)?.name||'本机账号'}</p><label>执行电脑<select value={agent.computerId||''} disabled={busy} onChange={e=>void run(()=>config({computerId:e.target.value}))}><option value="" disabled>尚未绑定</option>{state.collaboration?.computers?.filter(c=>c.ownerId===state.me?.id&&c.teamId===agent.teamId).map(c=><option key={c.id} value={c.id}>{c.name} · {c.online?'在线':'离线'}</option>)}</select></label><label>运行时<select aria-label="Agent 运行时" value={provider} onChange={e=>setProvider(e.target.value)}>{state.local.providers.filter(p=>p.available||p.id===agent.provider).map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select></label>{provider!==agent.provider&&<button className="button" disabled={busy} onClick={()=>life('switch')}>切换运行时，开始新会话</button>}<label>模型与推理强度<ProviderControls value={selection} onChange={setSelection} models={state.local.modelCatalogs?.[agent.provider]} loadModels={()=>call('provider.models',{provider:agent.provider,projectId:agent.projectId})}/></label><button className="button" disabled={busy} onClick={()=>void run(()=>call('lane.options',{sessionId:agent.sessionId,laneId:agent.sourceLaneId,...selection}))}>保存模型</button><div className="room-actions"><button className="button" disabled={busy} onClick={()=>life(agent.paused?'resume':'pause')}>{agent.paused?'恢复 Agent':'暂停 Agent'}</button><button className="button" disabled={busy} onClick={()=>life('reset')}>新会话，保留身份与记忆</button></div><small>旧会话归档保留。切换前需停止正在执行的任务。</small></div>}
 {tab==='协作'&&<div className="room-form"><label>什么时候回应<select aria-label="Agent 唤醒方式" value={trigger} onChange={e=>setTrigger(e.target.value as typeof trigger)}><option value="manual">仅手动运行</option><option value="mentions">被 @ 时回应</option><option value="discussion">参与项目群讨论</option></select></label><label><input type="checkbox" checked={autoTasks} onChange={e=>setAutoTasks(e.target.checked)}/>允许在这些项目里认领并开始任务</label><small>使用我的本机账号；最终产物仍由 DRI 审批。</small><label>每小时最多对话轮数<input type="number" min={1} max={120} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><fieldset><legend>参与项目</legend>{projects.map(p=><label key={p.id}><input type="checkbox" checked={projectIds.includes(p.id)} onChange={e=>setProjectIds(e.target.checked?[...projectIds,p.id]:projectIds.filter(id=>id!==p.id))}/>{p.name}</label>)}</fieldset><button className="button primary" disabled={busy} onClick={()=>void run(()=>config({policy:{trigger,autoTasks,maxTurnsPerHour:limit,projectIds}}))}>保存协作方式</button><small>群消息、提及、提醒按设置触发；暂停后不再唤醒。</small></div>}
 {tab==='记忆'&&<div className="room-form"><label>长期记忆<textarea aria-label="Agent 长期记忆" maxLength={20000} value={memory} onChange={e=>setMemory(e.target.value)} placeholder="例如：用简短中文；报价必须附来源；每次交付列出待确认事项。"/></label><small>由你维护，只用于此 Agent 的后续运行；不作为团队共享文件。重置模型会话会保留。</small><button className="button primary" disabled={busy} onClick={()=>void run(()=>config({memory}))}>保存记忆</button><button className="button" disabled={busy} onClick={()=>void run(()=>call('agent.workspace.open',{agentId}))}>打开 Agent 工作目录</button><small>项目产物仍在项目工作目录中，通过「产物」共享。</small></div>}
 {tab==='提醒'&&<div className="room-form"><label>跟进什么<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>什么时候<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>重复<select value={interval} onChange={e=>setInterval(Number(e.target.value))}><option value={0}>仅一次</option><option value={60}>每小时</option><option value={1440}>每天</option><option value={10080}>每周</option></select></label><button className="button primary" disabled={busy||!title.trim()||!dueAt} onClick={()=>void run(()=>call('collab.agent.reminder',{agentId,projectId:agent.projectId,title,dueAt:new Date(dueAt).toISOString(),intervalMinutes:interval,requestKey:crypto.randomUUID()}))}>添加跟进</button><small>需要电脑在线，并启用该项目的协作方式。</small>{state.collaboration?.agentReminders?.filter(r=>r.agentId===agentId).map(r=><div key={r.id} className="agent-event"><span>{r.title}<small>{new Date(r.dueAt).toLocaleString()} · {r.status}</small></span>{r.status==='scheduled'&&<><button className="inline-link" disabled={busy} onClick={()=>void run(()=>call('collab.agent.reminder',{agentId,id:r.id,dueAt:new Date(Date.now()+3600000).toISOString()}))}>推迟 1 小时</button><button className="inline-link" disabled={busy} onClick={()=>void run(()=>call('collab.agent.reminder',{agentId,id:r.id,cancel:true}))}>取消</button></>}</div>)}</div>}
 {tab==='工具'&&<div className="room-form"><p>为这位 Agent 配置本机环境变量和 MCP 应用。</p><button className="button" disabled={busy} onClick={()=>void run(async()=>setTools(JSON.stringify(await call('agent.tools.read',{agentId}),null,2)))}>读取本机配置</button><label>高级配置<textarea aria-label="Agent 工具配置" rows={12} spellCheck={false} value={tools} onChange={e=>setTools(e.target.value)} placeholder={'{\n  "env": {},\n  "mcpServers": {}\n}'}/></label><button className="button primary" disabled={busy||!tools.trim()} onClick={()=>void run(()=>call('agent.tools.save',{agentId,configuration:JSON.parse(tools)}))}>保存工具</button><small>加密保存在本机，不同步给同事。MCP 仅支持 Codex / Claude Code；第三方应用的登录由其 MCP 服务处理，下次运行生效。</small><details><summary>接入自行运行的 Agent</summary><p>把本地 Claude Code 或支持 MCP 的运行时接入此身份，由它领取并回传工作。</p><div className="room-actions"><button className="button" disabled={busy} onClick={()=>void run(async()=>setExternal(await call('agent.external.issue',{agentId})))}>生成 5 分钟接入码</button><button className="button" disabled={busy} onClick={()=>void run(async()=>setExternal(await call('agent.external.status',{agentId})))}>检查连接</button><button className="button" disabled={busy} onClick={()=>void run(async()=>{await call('agent.external.revoke',{agentId});setExternal(null);})}>断开并恢复托管</button></div>{external?.command&&<><label>1. 在本机终端运行<textarea readOnly rows={4} value={external.command}/></label><label>2. 加入外部运行时的 MCP 配置<textarea readOnly rows={8} value={JSON.stringify(external.mcp,null,2)}/></label><p>3. 让外部 Agent 调用 rpo_next 领取工作，完成后调用 rpo_reply 回传。应用须保持运行。</p></>}{external?.enabled!==undefined&&<p>{external.enabled?(external.connected?'已连接，最近有通信':'已授权，等待外部 Agent 调用'):'当前使用托管运行'}</p>}</details></div>}
 {tab==='活动'&&<div>{!events.length&&<p>还没有自动执行记录。可以在群里 @ 这位搭档。</p>}{events.map(e=><div key={e.id} className="agent-event"><span>{e.text.slice(0,150)}<small>{({queued:'等待电脑',running:'执行中',done:'已完成',failed:'失败',cancelled:'已取消'} as Record<string,string>)[e.status]} · {e.error||new Date(e.at).toLocaleString()}</small></span>{e.sessionId&&onOpenSession&&<button className="inline-link" onClick={()=>onOpenSession(e.sessionId!)}>打开记录</button>}</div>)}</div>}
 {error&&<p role="alert" className="room-error">{error}</p>}{saved&&<small role="status">{saved}</small>}
 </section>;
}
