import {useEffect,useState} from 'react';
import {GitBranch,FolderOpen,Github,ExternalLink,RefreshCw} from 'lucide-react';
import type {Call} from './ui';
type Context={root:string;gitRoot:string|null;branch:string|null;commit:string|null;detached:boolean;isWorktree:boolean;remote:string;repository:string|null;repositoryUrl:string|null};
export function ProjectContext({params,mapped,call,onMap}:{params:{workspaceId:string;sessionId:string;laneId?:string};mapped:boolean;call:Call;onMap:()=>void}){
 const [value,setValue]=useState<Context|null>(null),[error,setError]=useState('');const key=JSON.stringify(params);
 const refresh=async()=>{try{const next=await call('project.context',params);if(next){setValue(next);setError('');}}catch(e){setError(e instanceof Error?e.message:String(e));}};
 useEffect(()=>{let active=true;setValue(null);setError('');if(!mapped)return;const load=()=>void call('project.context',params).then(next=>{if(active&&next){setValue(next);setError('');}}).catch(e=>{if(active)setError(e.message);});load();window.addEventListener('focus',load);return()=>{active=false;window.removeEventListener('focus',load);};},[key,mapped]);
 return <div className="project-context-bar">{!mapped?<button onClick={onMap}><FolderOpen size={13}/>关联本机项目</button>:<details><summary title={value?.root||'当前 Agent 的工作目录'}>{value?.repository?<Github size={13}/>:<FolderOpen size={13}/>}<strong>{value?.repository||value?.root.split(/[\\/]/).pop()||'本机项目'}</strong><span><GitBranch size={12}/>{value?.branch||(value?.detached?value.commit?.slice(0,8):value?.gitRoot?'尚无提交':'非 Git 文件夹')}</span>{value?.isWorktree&&<span>独立工作树</span>}</summary><div className="project-context-popover"><dl><dt>GitHub 仓库</dt><dd>{value?.repository||'未关联 GitHub'}</dd><dt>本机工作目录</dt><dd>{value?.root||'读取中'}</dd><dt>分支</dt><dd>{value?.branch||(value?.detached?'分离 HEAD':'无')}</dd></dl><small>Agent 在本机目录执行；提交和推送后才更新 GitHub。</small>{error&&<p role="alert">{error}</p>}<footer><button title="刷新项目信息" onClick={()=>void refresh()}><RefreshCw size={13}/>刷新</button>{value?.repositoryUrl&&<button onClick={()=>void call('project.repository.open',params)}><ExternalLink size={13}/>打开 GitHub</button>}<button onClick={onMap}><FolderOpen size={13}/>更换目录</button></footer></div></details>}</div>;
}
